const cities = [
{"city":"'s-Hertogenbosch"},
{"city":"10th of Ramadan City"},
{"city":"Aachen"},
{"city":"Aalborg"},
{"city":"Aarhus"},
{"city":"Aba"},
{"city":"Abadan"},
{"city":"Abaetetuba"},
{"city":"Abbotsford"},
{"city":"Abbottabad"},
{"city":"Abeokuta"},
{"city":"Aberdeen"},
{"city":"Abha"},
{"city":"Abidjan"},
{"city":"Abiko"},
{"city":"Abilene"},
{"city":"Abu Dhabi"},
{"city":"Abuja"},
{"city":"Acapulco"},
{"city":"Acarigua"},
{"city":"Accra"},
{"city":"Adama"},
{"city":"Adana"},
{"city":"Adapazarı"},
{"city":"Addis Abeba"},
{"city":"Adelaide"},
{"city":"Aden"},
{"city":"Ado-Ekiti"},
{"city":"Adıyaman"},
{"city":"Afyonkarahisar"},
{"city":"Agadir"},
{"city":"Agartala"},
{"city":"Ageo"},
{"city":"Agra"},
{"city":"Aguascalientes"},
{"city":"Ahmedabad"},
{"city":"Ahmednagar"},
{"city":"Ahuachapán"},
{"city":"Ahvāz"},
{"city":"Aix-en-Provence"},
{"city":"Aizawl"},
{"city":"Aizuwakamatsu"},
{"city":"Ajlun"},
{"city":"Ajmer"},
{"city":"Ajmān"},
{"city":"Akaba"},
{"city":"Akashi"},
{"city":"Akhmim"},
{"city":"Akishima"},
{"city":"Akita"},
{"city":"Akola"},
{"city":"Akron"},
{"city":"Aksaray"},
{"city":"Akure"},
{"city":"Al Misratah"},
{"city":"Al Qadarif"},
{"city":"Al-Ain"},
{"city":"Al-Bab"},
{"city":"Al-Faw"},
{"city":"Al-Fayyum"},
{"city":"Al-Khobar"},
{"city":"Al-Kut"},
{"city":"Al-Mahalla al-Kubra"},
{"city":"Al-Mansura"},
{"city":"Al-Mukalla"},
{"city":"Al-Riffa"},
{"city":"Alagoinhas"},
{"city":"Alanya"},
{"city":"Alberton"},
{"city":"Albuquerque"},
{"city":"Aleksandria"},
{"city":"Aleppo"},
{"city":"Alexandria"},
{"city":"Algeciras"},
{"city":"Alger"},
{"city":"Alicante"},
{"city":"Aligarh"},
{"city":"Allegheny"},
{"city":"Allentown"},
{"city":"Almada"},
{"city":"Almaty"},
{"city":"Almere"},
{"city":"Almetjevsk"},
{"city":"Almirante Tamandaré"},
{"city":"Alor Star"},
{"city":"Alphen aan den Rijn"},
{"city":"Altamira, Pará"},
{"city":"Alvorada"},
{"city":"Alwar"},
{"city":"Amadora"},
{"city":"Amagasaki"},
{"city":"Amara"},
{"city":"Amarillo"},
{"city":"Amasya"},
{"city":"Ambato"},
{"city":"Americana"},
{"city":"Amiens"},
{"city":"Amman"},
{"city":"Amol"},
{"city":"Amravati"},
{"city":"Amritsar"},
{"city":"Amsterdam"},
{"city":"Anaco"},
{"city":"Anaheim"},
{"city":"Ananindeua"},
{"city":"Anantapur"},
{"city":"Anantnag"},
{"city":"Anchorage"},
{"city":"Ancona"},
{"city":"Anderlecht"},
{"city":"Andižan"},
{"city":"Andong"},
{"city":"Angeles"},
{"city":"Angers"},
{"city":"Angra dos Reis"},
{"city":"Anju"},
{"city":"Anjō"},
{"city":"Ankang"},
{"city":"Ankara"},
{"city":"Ann Arbor"},
{"city":"Annaba"},
{"city":"Annecy"},
{"city":"Anqing"},
{"city":"Ansan"},
{"city":"Anseong"},
{"city":"Anshan"},
{"city":"Anshun"},
{"city":"Antakya"},
{"city":"Antalya"},
{"city":"Antananarivo"},
{"city":"Antioch, California"},
{"city":"Antipolo"},
{"city":"Antofagasta"},
{"city":"Antsirabe"},
{"city":"Antwerpen"},
{"city":"Anyang"},
{"city":"Anápolis"},
{"city":"Aomori"},
{"city":"Aparecida de Goiânia"},
{"city":"Apatzingán"},
{"city":"Apeldoorn"},
{"city":"Apucarana"},
{"city":"Aqtaw"},
{"city":"Aqtöbe"},
{"city":"Aracaju"},
{"city":"Arad"},
{"city":"Araguari"},
{"city":"Araguaína"},
{"city":"Arak"},
{"city":"Arapiraca"},
{"city":"Arapongas"},
{"city":"Arar"},
{"city":"Araraquara"},
{"city":"Araras"},
{"city":"Araruama"},
{"city":"Araucária"},
{"city":"Araure"},
{"city":"Araxá"},
{"city":"Araçatuba"},
{"city":"Arbil"},
{"city":"Arequipa"},
{"city":"Argenteuil"},
{"city":"Arica"},
{"city":"Ariquemes"},
{"city":"Arish"},
{"city":"Arlington"},
{"city":"Armavir"},
{"city":"Armenia"},
{"city":"Arnhem"},
{"city":"Arusha"},
{"city":"Arvada"},
{"city":"As-Safira"},
{"city":"Asaba"},
{"city":"Asahikawa"},
{"city":"Asaka"},
{"city":"Asan"},
{"city":"Asansol"},
{"city":"Asella"},
{"city":"Ashdod"},
{"city":"Ashikaga"},
{"city":"Askalon"},
{"city":"Asmara"},
{"city":"Assis"},
{"city":"Assiut"},
{"city":"Assuan"},
{"city":"Astana"},
{"city":"Astrahan"},
{"city":"Asunción"},
{"city":"Atbara (kaupunki)"},
{"city":"Ateena"},
{"city":"Athens"},
{"city":"Atibaia"},
{"city":"Atlanta"},
{"city":"Atsugi"},
{"city":"Atıraw"},
{"city":"Atšinsk"},
{"city":"Auckland"},
{"city":"Augsburg"},
{"city":"Augusta"},
{"city":"Aurangabad"},
{"city":"Aurora"},
{"city":"Austin"},
{"city":"Awasa"},
{"city":"Awka"},
{"city":"Ayacucho"},
{"city":"Aydın"},
{"city":"Az Zubayr"},
{"city":"Azaz"},
{"city":"Aïn Beïda, Oum El Bouaghi"},
{"city":"Ağcabədi"},
{"city":"Ağrı"},
{"city":"Ašgabat"},
{"city":"Babol"},
{"city":"Babruisk"},
{"city":"Babylon"},
{"city":"Bacabal"},
{"city":"Bacolod"},
{"city":"Bacoor"},
{"city":"Bacău"},
{"city":"Badalona"},
{"city":"Bagdad"},
{"city":"Bago"},
{"city":"Baguio City"},
{"city":"Bagé"},
{"city":"Bahawalnagar"},
{"city":"Bahawalpur"},
{"city":"Bahir Dar"},
{"city":"Bahía Blanca"},
{"city":"Baia Mare"},
{"city":"Baicheng"},
{"city":"Baise"},
{"city":"Baishan"},
{"city":"Baiyin"},
{"city":"Bakersfield"},
{"city":"Baku"},
{"city":"Balakovo"},
{"city":"Balanga"},
{"city":"Balkanabat"},
{"city":"Ballarat"},
{"city":"Baltimore"},
{"city":"Balıkesir"},
{"city":"Bam"},
{"city":"Bamako"},
{"city":"Bamenda"},
{"city":"Ban Me Thuot"},
{"city":"Bandar Abbas"},
{"city":"Banfield"},
{"city":"Banfora"},
{"city":"Bangalore"},
{"city":"Bangkok"},
{"city":"Bangui"},
{"city":"Banha"},
{"city":"Banja Luka"},
{"city":"Banjarmasin"},
{"city":"Baoding"},
{"city":"Baoji"},
{"city":"Baoshan"},
{"city":"Baotou"},
{"city":"Baquba"},
{"city":"Barakaldo"},
{"city":"Baramulla"},
{"city":"Baranavitšy"},
{"city":"Barbacena"},
{"city":"Barcarena"},
{"city":"Barcelona"},
{"city":"Barcelos"},
{"city":"Bardhaman"},
{"city":"Bareilly"},
{"city":"Bari"},
{"city":"Barinas"},
{"city":"Barisal"},
{"city":"Barnaul"},
{"city":"Barquisimeto"},
{"city":"Barra Mansa"},
{"city":"Barranquilla"},
{"city":"Barreiras"},
{"city":"Barretos"},
{"city":"Barrie"},
{"city":"Bartın"},
{"city":"Barueri"},
{"city":"Barysau"},
{"city":"Basel"},
{"city":"Basel-Stadt"},
{"city":"Basra"},
{"city":"Bat Yam"},
{"city":"Bata"},
{"city":"Bataisk"},
{"city":"Batangas City"},
{"city":"Bathinda"},
{"city":"Batman"},
{"city":"Batna"},
{"city":"Baton Rouge"},
{"city":"Batumi"},
{"city":"Bauchi"},
{"city":"Bauru"},
{"city":"Bayamo"},
{"city":"Bayannur"},
{"city":"Bayawan"},
{"city":"Baybay"},
{"city":"Bayugan"},
{"city":"Bazhong"},
{"city":"Beaumont"},
{"city":"Beawar"},
{"city":"Beerseba"},
{"city":"Begusarai"},
{"city":"Behbahan"},
{"city":"Beida"},
{"city":"Beihai"},
{"city":"Beira"},
{"city":"Beirut"},
{"city":"Bejaïa"},
{"city":"Belfast"},
{"city":"Belford Roxo"},
{"city":"Belgaum"},
{"city":"Belgorod"},
{"city":"Belgrad"},
{"city":"Bellevue"},
{"city":"Belo Horizonte"},
{"city":"Belém"},
{"city":"Bendigo"},
{"city":"Bengasi"},
{"city":"Bengbu"},
{"city":"Benguela"},
{"city":"Beni Mellal"},
{"city":"Beni Suef"},
{"city":"Benin City"},
{"city":"Bento Gonçalves, Rio Grande do Sul"},
{"city":"Benxi"},
{"city":"Beppu"},
{"city":"Berazategui"},
{"city":"Berbera"},
{"city":"Berdjansk"},
{"city":"Berdsk"},
{"city":"Berezniki"},
{"city":"Bergamo"},
{"city":"Bergen"},
{"city":"Bergisch Gladbach"},
{"city":"Berkeley"},
{"city":"Berliini"},
{"city":"Bern"},
{"city":"Bernal"},
{"city":"Berrechid"},
{"city":"Bertoua"},
{"city":"Besançon"},
{"city":"Bet Shemesh"},
{"city":"Betim"},
{"city":"Bhagalpur"},
{"city":"Bharatpur"},
{"city":"Bharuch"},
{"city":"Bhilai"},
{"city":"Bhiwandi"},
{"city":"Bhiwani"},
{"city":"Bhopal"},
{"city":"Bhubaneswar"},
{"city":"Białystok"},
{"city":"Bibbin piirikunta"},
{"city":"Bielefeld"},
{"city":"Bielsko-Biała"},
{"city":"Bijapur"},
{"city":"Bijeljina"},
{"city":"Bijie"},
{"city":"Bijsk"},
{"city":"Bikaner"},
{"city":"Bilaspur, Chhattisgarh"},
{"city":"Bilbao"},
{"city":"Bilbays"},
{"city":"Billings"},
{"city":"Bimbo (Keski-Afrikka)"},
{"city":"Bingerville"},
{"city":"Bingöl"},
{"city":"Binzhou"},
{"city":"Biratnagar"},
{"city":"Birgunj"},
{"city":"Birjand"},
{"city":"Birkenhead"},
{"city":"Birmingham"},
{"city":"Biserta"},
{"city":"Biskra"},
{"city":"Bissau"},
{"city":"Biên Hòa"},
{"city":"Biñan"},
{"city":"Biškek"},
{"city":"Blantyre"},
{"city":"Blida"},
{"city":"Bloemfontein"},
{"city":"Blumenau"},
{"city":"Bnei Brak"},
{"city":"Bo"},
{"city":"Boa Vista"},
{"city":"Bobo Dioulasso"},
{"city":"Bochum"},
{"city":"Bogotá"},
{"city":"Bogra"},
{"city":"Boise"},
{"city":"Bojnurd"},
{"city":"Bokhtar"},
{"city":"Bologna"},
{"city":"Bolton"},
{"city":"Bolu"},
{"city":"Bolzano"},
{"city":"Bonn"},
{"city":"Bor"},
{"city":"Bordeaux"},
{"city":"Bordj Bou Arreridj"},
{"city":"Borujerd"},
{"city":"Boryeong"},
{"city":"Boston"},
{"city":"Bottrop"},
{"city":"Botucatu"},
{"city":"Bouaké"},
{"city":"Boulder"},
{"city":"Boulogne-Billancourt"},
{"city":"Bournemouth"},
{"city":"Bozhou"},
{"city":"Bradford"},
{"city":"Braga"},
{"city":"Bragança"},
{"city":"Bragança Paulista"},
{"city":"Brahmanbaria"},
{"city":"Brampton"},
{"city":"Brantford"},
{"city":"Brasília"},
{"city":"Bratislava"},
{"city":"Braunschweig"},
{"city":"Brazzaville"},
{"city":"Brașov"},
{"city":"Breda"},
{"city":"Bremen"},
{"city":"Bremerhaven"},
{"city":"Brescia"},
{"city":"Brest"},
{"city":"Bridgeport"},
{"city":"Bridgetown"},
{"city":"Brighton"},
{"city":"Brighton & Hove"},
{"city":"Brisbane"},
{"city":"Bristol"},
{"city":"Brjansk"},
{"city":"Brno"},
{"city":"Brockton"},
{"city":"Broken Arrow, Oklahoma"},
{"city":"Brownsville"},
{"city":"Brugge"},
{"city":"Brusque, Santa Catarina"},
{"city":"Bryssel"},
{"city":"Brysselin pääkaupunkialue"},
{"city":"Brăila"},
{"city":"Bucaramanga"},
{"city":"Bucheon"},
{"city":"Budapest"},
{"city":"Buea"},
{"city":"Buenos Aires"},
{"city":"Buffalo"},
{"city":"Buhara"},
{"city":"Bujumbura"},
{"city":"Bukan"},
{"city":"Bukarest"},
{"city":"Bukit Merah"},
{"city":"Bukit Mertajam"},
{"city":"Bulawayo"},
{"city":"Bumba (Kongon demokraattinen tasavalta)"},
{"city":"Bundi"},
{"city":"Buraidah"},
{"city":"Burbank"},
{"city":"Burco"},
{"city":"Burdur"},
{"city":"Burgas"},
{"city":"Burlington"},
{"city":"Burnaby"},
{"city":"Bursa"},
{"city":"Busan"},
{"city":"Butembo"},
{"city":"Butuan"},
{"city":"Butwal"},
{"city":"Buzău"},
{"city":"Bydgoszcz"},
{"city":"Bytom"},
{"city":"Béchar"},
{"city":"Băt Dâmbâng"},
{"city":"Būšehr"},
{"city":"Bắc Ninh"},
{"city":"Caaguazú"},
{"city":"Cabanatuan"},
{"city":"Cabimas"},
{"city":"Cabinda"},
{"city":"Cabo Frio"},
{"city":"Cabo de Santo Agostinho"},
{"city":"Cachoeirinha"},
{"city":"Cachoeiro de Itapemirim"},
{"city":"Cadiz"},
{"city":"Caen"},
{"city":"Cagayan de Oro"},
{"city":"Cagua"},
{"city":"Caguas"},
{"city":"Cairns"},
{"city":"Cajamarca"},
{"city":"Calabar"},
{"city":"Calabozo"},
{"city":"Calama"},
{"city":"Calamba"},
{"city":"Calapan"},
{"city":"Calbayog"},
{"city":"Calgary"},
{"city":"Cali"},
{"city":"Callao"},
{"city":"Caloocan"},
{"city":"Cam Ranh"},
{"city":"Camagüey"},
{"city":"Camaragibe"},
{"city":"Camaçari"},
{"city":"Cambridge"},
{"city":"Cambridge (Kanada)"},
{"city":"Cambé"},
{"city":"Cametá"},
{"city":"Campeche"},
{"city":"Campina Grande"},
{"city":"Campinas"},
{"city":"Campo Grande"},
{"city":"Campo Largo"},
{"city":"Campos dos Goytacazes"},
{"city":"Canberra"},
{"city":"Cancún"},
{"city":"Cangzhou"},
{"city":"Canoas"},
{"city":"Cap-Haïtien"},
{"city":"Cape Coral"},
{"city":"Caracas"},
{"city":"Caraguatatuba"},
{"city":"Carapicuíba"},
{"city":"Carcar"},
{"city":"Cardiff"},
{"city":"Cariacica"},
{"city":"Carlsbad (Kalifornia)"},
{"city":"Carora"},
{"city":"Carrefour"},
{"city":"Cartagena"},
{"city":"Caruaru"},
{"city":"Carúpano"},
{"city":"Casablanca"},
{"city":"Cascavel"},
{"city":"Castanhal"},
{"city":"Castelar"},
{"city":"Castellón de la Plana"},
{"city":"Catalão"},
{"city":"Catamarca"},
{"city":"Catanduva"},
{"city":"Catania"},
{"city":"Catbalogan"},
{"city":"Cauayan"},
{"city":"Caucaia"},
{"city":"Cavite City"},
{"city":"Caxias"},
{"city":"Caxias do Sul"},
{"city":"Cebu"},
{"city":"Cedar Rapids"},
{"city":"Centennial (Colorado)"},
{"city":"Ceyhan"},
{"city":"Ch'ŏngjin"},
{"city":"Chabahar"},
{"city":"Chaman"},
{"city":"Chandigarh"},
{"city":"Chandler"},
{"city":"Changchun"},
{"city":"Changde"},
{"city":"Changhua"},
{"city":"Changsha"},
{"city":"Changshu"},
{"city":"Changwon"},
{"city":"Changzhi"},
{"city":"Changzhou"},
{"city":"Chaoyang"},
{"city":"Chaozhou"},
{"city":"Chapecó"},
{"city":"Charallave"},
{"city":"Charleroi"},
{"city":"Charleston"},
{"city":"Charlotte"},
{"city":"Charsadda"},
{"city":"Chatham-Kent"},
{"city":"Chattanooga"},
{"city":"Chelmsford"},
{"city":"Cheltenham"},
{"city":"Chemnitz"},
{"city":"Chengde"},
{"city":"Chengdu"},
{"city":"Chennai"},
{"city":"Chenzhou"},
{"city":"Cheonan"},
{"city":"Cheongju"},
{"city":"Chesapeake"},
{"city":"Chetumal"},
{"city":"Chiang Mai"},
{"city":"Chiayi City"},
{"city":"Chiba"},
{"city":"Chicago"},
{"city":"Chiclayo"},
{"city":"Chico"},
{"city":"Chifeng"},
{"city":"Chigasaki"},
{"city":"Chihuahua"},
{"city":"Chikushino"},
{"city":"Chillán"},
{"city":"Chimbote"},
{"city":"Chimoio"},
{"city":"Chinandega"},
{"city":"Chingola"},
{"city":"Chiniot"},
{"city":"Chittagong"},
{"city":"Chittoor"},
{"city":"Chizhou"},
{"city":"Chișinău"},
{"city":"Choluteca"},
{"city":"Chongju"},
{"city":"Chongqing"},
{"city":"Chongzuo"},
{"city":"Chorzów"},
{"city":"Christchurch"},
{"city":"Chula Vista"},
{"city":"Chuncheon"},
{"city":"Chungju"},
{"city":"Chuzhou"},
{"city":"Chōfu"},
{"city":"Cianjur"},
{"city":"Ciego de Ávila"},
{"city":"Cienfuegos"},
{"city":"Cincinnati"},
{"city":"City of Westminster"},
{"city":"Ciudad Acuña"},
{"city":"Ciudad Bolívar"},
{"city":"Ciudad Guayana"},
{"city":"Ciudad Juárez"},
{"city":"Ciudad Obregón"},
{"city":"Ciudad Urdaneta"},
{"city":"Ciudad de la Costa"},
{"city":"Ciudad del Carmen"},
{"city":"Ciudad del Este"},
{"city":"Cixi City"},
{"city":"Clarksville"},
{"city":"Clearwater"},
{"city":"Clermont-Ferrand"},
{"city":"Cleveland"},
{"city":"Cluj-Napoca"},
{"city":"Coatzacoalcos"},
{"city":"Cochabamba"},
{"city":"Codó"},
{"city":"Coimbatore"},
{"city":"Coimbra"},
{"city":"Colatina"},
{"city":"Colchester"},
{"city":"Colima"},
{"city":"Colina"},
{"city":"Colombo"},
{"city":"Colorado Springs"},
{"city":"Columbia"},
{"city":"Columbus"},
{"city":"Colón"},
{"city":"Comayagua"},
{"city":"Comilla"},
{"city":"Comitán"},
{"city":"Comodoro Rivadavia"},
{"city":"Conakry"},
{"city":"Concepción"},
{"city":"Concord"},
{"city":"Concordia"},
{"city":"Conselheiro Lafaiete"},
{"city":"Constantine"},
{"city":"Constanța"},
{"city":"Contagem"},
{"city":"Copiapó"},
{"city":"Coquimbo"},
{"city":"Coquitlam"},
{"city":"Coral Springs"},
{"city":"Cork"},
{"city":"Coro"},
{"city":"Corona"},
{"city":"Coronel"},
{"city":"Coronel Fabriciano"},
{"city":"Corpus Christi"},
{"city":"Corrientes"},
{"city":"Costa Mesa"},
{"city":"Cotabato City"},
{"city":"Cotia"},
{"city":"Cotonou"},
{"city":"Coventry"},
{"city":"Cox's Bazar"},
{"city":"Craiova"},
{"city":"Crato"},
{"city":"Criciúma"},
{"city":"Cubatão"},
{"city":"Cuenca"},
{"city":"Cuiabá"},
{"city":"Culiacán"},
{"city":"Cumaná"},
{"city":"Curicó"},
{"city":"Curitiba"},
{"city":"Cusco"},
{"city":"Cuttack"},
{"city":"Częstochowa"},
{"city":"Cà Mau"},
{"city":"Córdoba"},
{"city":"Cúa"},
{"city":"Cúcuta"},
{"city":"Cần Thơ"},
{"city":"Cẩm Phả"},
{"city":"Dadu"},
{"city":"Daegu"},
{"city":"Daejeon"},
{"city":"Dagupan"},
{"city":"Dahuk"},
{"city":"Daitō"},
{"city":"Dakar"},
{"city":"Dakhla"},
{"city":"Dalian"},
{"city":"Dallas"},
{"city":"Daly City"},
{"city":"Damanhur"},
{"city":"Damaskos"},
{"city":"Damietta"},
{"city":"Dammam"},
{"city":"Danao"},
{"city":"Dandong"},
{"city":"Dangjin"},
{"city":"Danzhou"},
{"city":"Daqing"},
{"city":"Dar es Salaam"},
{"city":"Daraa"},
{"city":"Darjeeling"},
{"city":"Darmstadt"},
{"city":"Darwin"},
{"city":"Dasmariñas"},
{"city":"Datong"},
{"city":"Davao"},
{"city":"Davenport"},
{"city":"Dawei"},
{"city":"Dayton"},
{"city":"Dazhou"},
{"city":"Daşoguz"},
{"city":"Dearborn"},
{"city":"Debrecen"},
{"city":"Dehradun"},
{"city":"Deir ez Zor"},
{"city":"Delft"},
{"city":"Delhi"},
{"city":"Delmas"},
{"city":"Delta"},
{"city":"Dengzhou"},
{"city":"Denizli"},
{"city":"Denton"},
{"city":"Denver"},
{"city":"Deoghar"},
{"city":"Dera Ghazi Khan"},
{"city":"Dera Ismail Khan"},
{"city":"Derbent"},
{"city":"Derby"},
{"city":"Des Moines"},
{"city":"Dessie"},
{"city":"Detroit"},
{"city":"Deventer"},
{"city":"Deyang"},
{"city":"Dezful"},
{"city":"Dezhou"},
{"city":"Dhahran"},
{"city":"Dhaka"},
{"city":"Dhamar"},
{"city":"Dhangadhi"},
{"city":"Dharan"},
{"city":"Diadema, São Paulo"},
{"city":"Dibrugarh"},
{"city":"Digos"},
{"city":"Dijon"},
{"city":"Dili"},
{"city":"Dimitrovgrad"},
{"city":"Dinajpur"},
{"city":"Dingxi"},
{"city":"Dingzhou"},
{"city":"Diourbel"},
{"city":"Dipolog"},
{"city":"Dire Dawa"},
{"city":"Disuk"},
{"city":"Divinópolis"},
{"city":"Divo, Ivory Coast"},
{"city":"Diwaniyya"},
{"city":"Diyarbakır"},
{"city":"Djelfa"},
{"city":"Djibouti"},
{"city":"Dnipro"},
{"city":"Dobritš"},
{"city":"Dodoma"},
{"city":"Doha"},
{"city":"Dolisie"},
{"city":"Doncaster"},
{"city":"Donetsk"},
{"city":"Dongguan"},
{"city":"Dongying"},
{"city":"Donin Rostov"},
{"city":"Dordrecht"},
{"city":"Dortmund"},
{"city":"Douala"},
{"city":"Dourados"},
{"city":"Downey"},
{"city":"Dresden"},
{"city":"Dubai"},
{"city":"Dublin"},
{"city":"Duisburg"},
{"city":"Dum Dum (Intia)"},
{"city":"Duma"},
{"city":"Dumaguete"},
{"city":"Dundee"},
{"city":"Dunedin"},
{"city":"Duque de Caxias"},
{"city":"Durango"},
{"city":"Durban"},
{"city":"Durg"},
{"city":"Durgapur"},
{"city":"Durham"},
{"city":"Durrës"},
{"city":"Dutse"},
{"city":"Duvalin piirikunta (Florida)"},
{"city":"Dušanbe"},
{"city":"Düsseldorf"},
{"city":"Düzce"},
{"city":"Dąbrowa Górnicza"},
{"city":"East London"},
{"city":"Eastbourne"},
{"city":"Ebetsu"},
{"city":"Ebina"},
{"city":"Edfu"},
{"city":"Edinburg"},
{"city":"Edinburgh"},
{"city":"Edirne"},
{"city":"Edmonton"},
{"city":"Edéa"},
{"city":"Eindhoven"},
{"city":"Ejido, Venezuela"},
{"city":"Ekibastuz"},
{"city":"El Aaiún"},
{"city":"El Alto"},
{"city":"El Cajon"},
{"city":"El Jadida"},
{"city":"El Limón piñal"},
{"city":"El Monte"},
{"city":"El Obeid"},
{"city":"El Oued"},
{"city":"El Paso"},
{"city":"El Tigre"},
{"city":"Elbląg"},
{"city":"Elche"},
{"city":"Eldoret"},
{"city":"Elgin"},
{"city":"Elista"},
{"city":"Elizabeth"},
{"city":"Eluru"},
{"city":"Elâzığ"},
{"city":"Embu das Artes"},
{"city":"Engels"},
{"city":"English Bazar"},
{"city":"Enschede"},
{"city":"Ensenada"},
{"city":"Enugu"},
{"city":"Erdenet"},
{"city":"Erechim"},
{"city":"Erfurt"},
{"city":"Erie"},
{"city":"Erlangen"},
{"city":"Erode"},
{"city":"Erzincan"},
{"city":"Erzurum"},
{"city":"Esbjerg"},
{"city":"Escondido"},
{"city":"Escuintla"},
{"city":"Eskişehir"},
{"city":"Eslamshahr"},
{"city":"Esmeraldas"},
{"city":"Espoo"},
{"city":"Essen"},
{"city":"Estelí"},
{"city":"Eugene"},
{"city":"Eunápolis"},
{"city":"Evansville"},
{"city":"Everett"},
{"city":"Exeter"},
{"city":"Ezhou"},
{"city":"Eṣfahān"},
{"city":"Fairfield"},
{"city":"Faisalabad"},
{"city":"Falluja"},
{"city":"Fangchenggang"},
{"city":"Fargo"},
{"city":"Faridabad"},
{"city":"Feira de Santana"},
{"city":"Fergana"},
{"city":"Ferrara"},
{"city":"Ferraz de Vasconcelos"},
{"city":"Fethiye"},
{"city":"Fier"},
{"city":"Firenze"},
{"city":"Florencia"},
{"city":"Florencio Varela"},
{"city":"Florianópolis"},
{"city":"Foggia"},
{"city":"Fontana"},
{"city":"Forlì"},
{"city":"Formosa"},
{"city":"Fort Collins"},
{"city":"Fort Lauderdale"},
{"city":"Fort Wayne"},
{"city":"Fort Worth"},
{"city":"Fortaleza"},
{"city":"Foshan"},
{"city":"Foz do Iguaçu"},
{"city":"Franca"},
{"city":"Francisco Morato"},
{"city":"Franco da Rocha"},
{"city":"Frankfurt am Main"},
{"city":"Frederiksberg"},
{"city":"Freetown"},
{"city":"Freiburg im Breisgau"},
{"city":"Fremont"},
{"city":"Fresno"},
{"city":"Frisco"},
{"city":"Fuchū"},
{"city":"Fuenlabrada"},
{"city":"Fuji"},
{"city":"Fujieda"},
{"city":"Fujimi"},
{"city":"Fujimino"},
{"city":"Fujinomiya"},
{"city":"Fujisawa"},
{"city":"Fukaya"},
{"city":"Fukui"},
{"city":"Fukuoka"},
{"city":"Fukushima"},
{"city":"Fukuyama"},
{"city":"Fullerton"},
{"city":"Funabashi"},
{"city":"Funchal"},
{"city":"Fushun"},
{"city":"Fuxin"},
{"city":"Fuyang"},
{"city":"Fuzhou"},
{"city":"Fuzhou (Jiangxi)"},
{"city":"Fès"},
{"city":"Fës"},
{"city":"Fürth"},
{"city":"Gaborone"},
{"city":"Gainesville"},
{"city":"Galați"},
{"city":"Gandhinagar"},
{"city":"Gangneung"},
{"city":"Gangtok"},
{"city":"Ganzhou"},
{"city":"Gapan"},
{"city":"Garanhuns"},
{"city":"Garden Grove"},
{"city":"Garland"},
{"city":"Garoua"},
{"city":"Gatineau"},
{"city":"Gaya"},
{"city":"Gaza"},
{"city":"Gaziantep"},
{"city":"Gdańsk"},
{"city":"Gdynia"},
{"city":"Geelong"},
{"city":"Gelsenkirchen"},
{"city":"General Roca"},
{"city":"General Santos"},
{"city":"Geneve"},
{"city":"Genova"},
{"city":"Gent"},
{"city":"Geoje"},
{"city":"George"},
{"city":"George Town"},
{"city":"Georgetown"},
{"city":"Ghardaïa"},
{"city":"Gharyan"},
{"city":"Ghaziabad"},
{"city":"Ghazipur"},
{"city":"Ghazni"},
{"city":"Gifu"},
{"city":"Gimhae"},
{"city":"Gimpo"},
{"city":"Gingoog"},
{"city":"Giresun"},
{"city":"Girga"},
{"city":"Gisenyi"},
{"city":"Gitega"},
{"city":"Giugliano in Campania"},
{"city":"Giza"},
{"city":"Gjumri"},
{"city":"Glasgow"},
{"city":"Glendale"},
{"city":"Gliwice"},
{"city":"Gloucester"},
{"city":"Godhra"},
{"city":"Goiânia"},
{"city":"Gojra"},
{"city":"Gold Coast"},
{"city":"Golmud"},
{"city":"Goma"},
{"city":"Gonaïves"},
{"city":"Gonbad-e Qabus"},
{"city":"Gondar"},
{"city":"Gondomar"},
{"city":"Gongju"},
{"city":"Gongzhuling"},
{"city":"González Catán"},
{"city":"Gorakhpur"},
{"city":"Gorgān"},
{"city":"Gorzów Wielkopolski"},
{"city":"Governador Valadares"},
{"city":"Goyang"},
{"city":"Gqeberha"},
{"city":"Granada"},
{"city":"Grand Rapids"},
{"city":"Gravataí"},
{"city":"Graz"},
{"city":"Greater Sudbury"},
{"city":"Green Bay"},
{"city":"Greensboro"},
{"city":"Gregorio de Laferrère"},
{"city":"Grenoble"},
{"city":"Groningen"},
{"city":"Groznyi"},
{"city":"Guacara"},
{"city":"Guadalajara"},
{"city":"Guadalupe, Nuevo León"},
{"city":"Gualeguaychú"},
{"city":"Guanare"},
{"city":"Guangyuan"},
{"city":"Guang’an"},
{"city":"Guantánamo"},
{"city":"Guarapari"},
{"city":"Guarapuava"},
{"city":"Guarenas"},
{"city":"Guarulhos"},
{"city":"Guatemala"},
{"city":"Guatire"},
{"city":"Guayaquil"},
{"city":"Guelph"},
{"city":"Guigang"},
{"city":"Guihulngan"},
{"city":"Guilin"},
{"city":"Guimarães"},
{"city":"Guiyang"},
{"city":"Gujranwala"},
{"city":"Gujrat"},
{"city":"Gulu"},
{"city":"Gumi"},
{"city":"Gunpo"},
{"city":"Gunsan"},
{"city":"Guntur"},
{"city":"Gurgaon"},
{"city":"Guri"},
{"city":"Gusau"},
{"city":"Guwahati"},
{"city":"Guyuan"},
{"city":"Guéckédou"},
{"city":"Gwalior"},
{"city":"Gwangju"},
{"city":"Gwangju, Gyeonggi"},
{"city":"Gwangmyeong"},
{"city":"Gwangyang"},
{"city":"Gweru"},
{"city":"Gyeongju"},
{"city":"Gyeongsan"},
{"city":"Győr"},
{"city":"Göteborg"},
{"city":"Göttingen"},
{"city":"Gütersloh"},
{"city":"Gəncə"},
{"city":"Haag"},
{"city":"Haarlem"},
{"city":"Habarovsk"},
{"city":"Habikino"},
{"city":"Hachinohe"},
{"city":"Hachiōji"},
{"city":"Hadano"},
{"city":"Haeju"},
{"city":"Hagen"},
{"city":"Haicheng"},
{"city":"Haidong"},
{"city":"Haifa"},
{"city":"Haikou"},
{"city":"Hakodate"},
{"city":"Hakusan"},
{"city":"Halifax"},
{"city":"Halle (Saale)"},
{"city":"Hama"},
{"city":"Hamamatsu"},
{"city":"Hamedan"},
{"city":"Hamhŭng"},
{"city":"Hami"},
{"city":"Hamilton"},
{"city":"Hamm"},
{"city":"Hampton (Virginia)"},
{"city":"Hampuri"},
{"city":"Hanam"},
{"city":"Hanau"},
{"city":"Hanchuan City"},
{"city":"Handa"},
{"city":"Handan"},
{"city":"Hangzhou"},
{"city":"Hannover"},
{"city":"Hanoi"},
{"city":"Hanumangarh"},
{"city":"Hanzhong"},
{"city":"Harar"},
{"city":"Harare"},
{"city":"Harbin"},
{"city":"Hargeisa"},
{"city":"Harkova"},
{"city":"Hartford"},
{"city":"Hasaka"},
{"city":"Hasavjurt"},
{"city":"Hat Yai"},
{"city":"Hatsukaichi"},
{"city":"Havanna"},
{"city":"Hayward"},
{"city":"Ha’il"},
{"city":"Hebi"},
{"city":"Hebron"},
{"city":"Hechi"},
{"city":"Hefei"},
{"city":"Hegang"},
{"city":"Heidelberg"},
{"city":"Heihe"},
{"city":"Heilbronn"},
{"city":"Helsingborg"},
{"city":"Helsinki"},
{"city":"Helwan"},
{"city":"Henderson"},
{"city":"Hengshui"},
{"city":"Hengyang"},
{"city":"Herat"},
{"city":"Hermosillo"},
{"city":"Herne"},
{"city":"Heroica Guaymas"},
{"city":"Heyuan"},
{"city":"Heze"},
{"city":"Hezhou"},
{"city":"Hialeah"},
{"city":"Higashihiroshima"},
{"city":"Higashikurume"},
{"city":"Higashimurayama"},
{"city":"Higashiōmi"},
{"city":"Higashiōsaka"},
{"city":"High Point"},
{"city":"Hikone"},
{"city":"Hildesheim"},
{"city":"Hilla"},
{"city":"Himamaylan"},
{"city":"Himeji"},
{"city":"Hino"},
{"city":"Hirakata"},
{"city":"Hiratsuka"},
{"city":"Hirosaki"},
{"city":"Hiroshima"},
{"city":"Hisar"},
{"city":"Hitachi"},
{"city":"Hitachinaka"},
{"city":"Hiva"},
{"city":"Hobart"},
{"city":"Hodeida"},
{"city":"Hoeryŏng"},
{"city":"Hohhot"},
{"city":"Holguín"},
{"city":"Hollywood"},
{"city":"Holon"},
{"city":"Homel"},
{"city":"Homs"},
{"city":"Hongkong"},
{"city":"Honolulu"},
{"city":"Honolulun piirikunta"},
{"city":"Hortolândia"},
{"city":"Houston"},
{"city":"Howrah"},
{"city":"Hpa-An"},
{"city":"Hrodna"},
{"city":"Hsinchu"},
{"city":"Huacho"},
{"city":"Huaibei"},
{"city":"Huaihua"},
{"city":"Huainan"},
{"city":"Huai’an"},
{"city":"Huambo"},
{"city":"Huancayo"},
{"city":"Huanggang"},
{"city":"Huangshan (kaupunki)"},
{"city":"Huangshi"},
{"city":"Huaraz"},
{"city":"Huazhou"},
{"city":"Huddersfield"},
{"city":"Hudžand"},
{"city":"Huehuetenango"},
{"city":"Huizhou"},
{"city":"Huludao"},
{"city":"Hulunbuir"},
{"city":"Hunchun"},
{"city":"Huntington Beach"},
{"city":"Huntsville"},
{"city":"Hurghada"},
{"city":"Huzhou"},
{"city":"Huánuco"},
{"city":"Huế"},
{"city":"Hwaseong"},
{"city":"Hyderabad"},
{"city":"Hyesan"},
{"city":"Hòa Bình"},
{"city":"Hōfu"},
{"city":"Hŭich'ŏn"},
{"city":"Hải Dương"},
{"city":"Hải Phòng"},
{"city":"Hồ Chí Minhin kaupunki"},
{"city":"Hội An"},
{"city":"Iași"},
{"city":"Ibadan"},
{"city":"Ibagué"},
{"city":"Ibaraki"},
{"city":"Ibarra"},
{"city":"Ibb"},
{"city":"Ibirité"},
{"city":"Ica"},
{"city":"Icheon"},
{"city":"Ichihara"},
{"city":"Ichikawa"},
{"city":"Ichinomiya"},
{"city":"Ichinoseki"},
{"city":"Idlib"},
{"city":"Ife"},
{"city":"Igarassu"},
{"city":"Iguala"},
{"city":"Iizuka"},
{"city":"Ikeda"},
{"city":"Ikeja"},
{"city":"Ikoma"},
{"city":"Iksan"},
{"city":"Ilagan"},
{"city":"Ilam"},
{"city":"Ilhéus"},
{"city":"Iligan"},
{"city":"Iloilo City"},
{"city":"Ilorin"},
{"city":"Imabari"},
{"city":"Imperatriz"},
{"city":"Imphal"},
{"city":"Imus"},
{"city":"Inazawa"},
{"city":"Incheon"},
{"city":"Indaiatuba"},
{"city":"Independence"},
{"city":"Indianapolis"},
{"city":"Indore"},
{"city":"Indramayu"},
{"city":"Inglewood"},
{"city":"Ingolstadt"},
{"city":"Innsbruck"},
{"city":"Inzai"},
{"city":"Ipatinga"},
{"city":"Ipoh"},
{"city":"Ipswich"},
{"city":"Iquique"},
{"city":"Iquitos"},
{"city":"Iraklion"},
{"city":"Irapuato"},
{"city":"Irbid"},
{"city":"Iriga"},
{"city":"Irkutsk"},
{"city":"Iruma"},
{"city":"Irvine"},
{"city":"Irving"},
{"city":"Isabela"},
{"city":"Isahaya"},
{"city":"Ise"},
{"city":"Isehara"},
{"city":"Isesaki"},
{"city":"Ishinomaki"},
{"city":"Isidro Casanova"},
{"city":"Islamabad"},
{"city":"Ismaïlia"},
{"city":"Isparta"},
{"city":"Istanbul"},
{"city":"Itabira"},
{"city":"Itaboraí"},
{"city":"Itabuna"},
{"city":"Itaguaí"},
{"city":"Italia"},
{"city":"Itami"},
{"city":"Itapecerica da Serra"},
{"city":"Itapetininga"},
{"city":"Itapevi"},
{"city":"Itapipoca"},
{"city":"Itaquaquecetuba"},
{"city":"Itatiba"},
{"city":"Itu"},
{"city":"Ituiutaba"},
{"city":"Itumbiara"},
{"city":"Ituzaingó"},
{"city":"Itä-Berliini"},
{"city":"Ivano-Frankivsk"},
{"city":"Iwaki"},
{"city":"Iwakuni"},
{"city":"Iwata"},
{"city":"Izumi"},
{"city":"Izumo"},
{"city":"Iğdır"},
{"city":"Iževsk"},
{"city":"Jabalpur"},
{"city":"Jaboatão dos Guararapes"},
{"city":"Jacareí"},
{"city":"Jackson"},
{"city":"Jacksonville"},
{"city":"Jacobabad"},
{"city":"Jaipur"},
{"city":"Jakarta"},
{"city":"Jakutsk"},
{"city":"Jalalabad"},
{"city":"Jalandhar"},
{"city":"Jalgaon"},
{"city":"Jalingo"},
{"city":"Jammu"},
{"city":"Jamnagar"},
{"city":"Jamshedpur"},
{"city":"Jandira"},
{"city":"Jaraguá do Sul"},
{"city":"Jaramana"},
{"city":"Jaranwala"},
{"city":"Jaroslavl"},
{"city":"Jaú"},
{"city":"Jecheon"},
{"city":"Jedda"},
{"city":"Jeju"},
{"city":"Jekaterinburg"},
{"city":"Jena"},
{"city":"Jeongeup"},
{"city":"Jeonju"},
{"city":"Jequié"},
{"city":"Jerevan"},
{"city":"Jerez de la Frontera"},
{"city":"Jersey City"},
{"city":"Jerusalem"},
{"city":"Jessore"},
{"city":"Jevpatorija"},
{"city":"Jhansi"},
{"city":"Ji'an"},
{"city":"Ji-Paraná"},
{"city":"Jiamusi"},
{"city":"Jiangmen"},
{"city":"Jiangyin"},
{"city":"Jianyang, Sichuan"},
{"city":"Jiaozuo"},
{"city":"Jiaxing"},
{"city":"Jiayuguan"},
{"city":"Jieyang"},
{"city":"Jijiga"},
{"city":"Jilin"},
{"city":"Jimma"},
{"city":"Jinan"},
{"city":"Jinchang"},
{"city":"Jincheng"},
{"city":"Jingdezhen"},
{"city":"Jingmen"},
{"city":"Jingzhou"},
{"city":"Jinhua"},
{"city":"Jining"},
{"city":"Jinjiang"},
{"city":"Jinju"},
{"city":"Jinzhong"},
{"city":"Jinzhou"},
{"city":"Jiujiang"},
{"city":"Jiuquan"},
{"city":"Jixi"},
{"city":"Jizan"},
{"city":"Jizzax"},
{"city":"Ji’an"},
{"city":"Jodhpur"},
{"city":"Johannesburg"},
{"city":"Johor Bahru"},
{"city":"Joinville"},
{"city":"Jokohama"},
{"city":"Joliet"},
{"city":"Jos"},
{"city":"José C. Paz"},
{"city":"Jounieh"},
{"city":"João Pessoa"},
{"city":"Joškar-Ola"},
{"city":"Juazeiro"},
{"city":"Juazeiro do Norte"},
{"city":"Juba"},
{"city":"Jubail"},
{"city":"Juiz de Fora"},
{"city":"Juliaca"},
{"city":"Junagadh"},
{"city":"Jundiaí"},
{"city":"Jurupa Valley"},
{"city":"Juticalpa"},
{"city":"Južno-Sahalinsk"},
{"city":"Jyväskylä"},
{"city":"Jōetsu"},
{"city":"Kabankalan"},
{"city":"Kabul"},
{"city":"Kabwe"},
{"city":"Kadapa"},
{"city":"Kadoma"},
{"city":"Kaduna"},
{"city":"Kaech'ŏn"},
{"city":"Kagoshima"},
{"city":"Kahama"},
{"city":"Kahramanmaraş"},
{"city":"Kaifeng"},
{"city":"Kairo"},
{"city":"Kaiserslautern"},
{"city":"Kakamigahara"},
{"city":"Kakegawa"},
{"city":"Kakinada"},
{"city":"Kakogawa"},
{"city":"Kalemie"},
{"city":"Kaliningrad"},
{"city":"Kalkutta"},
{"city":"Kallithea"},
{"city":"Kaluga"},
{"city":"Kamagaya"},
{"city":"Kamakura"},
{"city":"Kamensk-Uralski"},
{"city":"Kamishli"},
{"city":"Kamjanets-Podilskyi"},
{"city":"Kampala"},
{"city":"Kamyšin"},
{"city":"Kananga"},
{"city":"Kanasín"},
{"city":"Kanazawa"},
{"city":"Kanchipuram"},
{"city":"Kandahar"},
{"city":"Kandy"},
{"city":"Kanggye"},
{"city":"Kannur"},
{"city":"Kano"},
{"city":"Kanoya"},
{"city":"Kanpur"},
{"city":"Kansas City"},
{"city":"Kanton"},
{"city":"Kaohsiung"},
{"city":"Kaolack"},
{"city":"Kapkaupunki"},
{"city":"Karabük"},
{"city":"Karachi"},
{"city":"Karadeniz Ereğli"},
{"city":"Karaganda"},
{"city":"Karaj"},
{"city":"Karaman"},
{"city":"Karamay"},
{"city":"Karatsu"},
{"city":"Karbala"},
{"city":"Karimnagar"},
{"city":"Kariya"},
{"city":"Karlsruhe"},
{"city":"Kars"},
{"city":"Kasama"},
{"city":"Kashan"},
{"city":"Kashihara"},
{"city":"Kashiwa"},
{"city":"Kaspijsk"},
{"city":"Kassala"},
{"city":"Kassel"},
{"city":"Kastamonu"},
{"city":"Kasuga"},
{"city":"Kasugai"},
{"city":"Kasukabe"},
{"city":"Kasulu"},
{"city":"Kasur"},
{"city":"Kathmandu"},
{"city":"Katowice"},
{"city":"Katsina"},
{"city":"Kaunas"},
{"city":"Kawachinagano"},
{"city":"Kawagoe"},
{"city":"Kawaguchi"},
{"city":"Kawanishi"},
{"city":"Kawasaki"},
{"city":"Kaya"},
{"city":"Kayseri"},
{"city":"Kazan"},
{"city":"Kazo"},
{"city":"Kaôh Kông"},
{"city":"Kašgar"},
{"city":"Kecskemét"},
{"city":"Keelung"},
{"city":"Kelowna"},
{"city":"Kenema"},
{"city":"Kenitra"},
{"city":"Keren"},
{"city":"Kerman"},
{"city":"Kermānšāh"},
{"city":"Kertš"},
{"city":"Kfar Saba"},
{"city":"Khairpur"},
{"city":"Khamis Mushayt"},
{"city":"Khan Yunis"},
{"city":"Khartum"},
{"city":"Khemisset"},
{"city":"Khenchela"},
{"city":"Khenifra"},
{"city":"Khomeynishahr"},
{"city":"Khon Kaen"},
{"city":"Khorramabad"},
{"city":"Khost"},
{"city":"Khoy"},
{"city":"Khulna"},
{"city":"Khuzdar"},
{"city":"Kidapawan"},
{"city":"Kiel"},
{"city":"Kielce"},
{"city":"Kiffa"},
{"city":"Kigali"},
{"city":"Kigoma"},
{"city":"Kilis"},
{"city":"Killeen"},
{"city":"Kimch'aek"},
{"city":"Kindu"},
{"city":"Kingston"},
{"city":"Kingston upon Hull"},
{"city":"Kinshasa"},
{"city":"Kioto"},
{"city":"Kiova"},
{"city":"Kira Town"},
{"city":"Kirishima"},
{"city":"Kirkuk"},
{"city":"Kirov"},
{"city":"Kiryū"},
{"city":"Kisangani"},
{"city":"Kisarazu"},
{"city":"Kishiwada"},
{"city":"Kisii"},
{"city":"Kismayo"},
{"city":"Kisumu"},
{"city":"Kitakyūshū"},
{"city":"Kitami"},
{"city":"Kitchener"},
{"city":"Kitwe"},
{"city":"Klagenfurt"},
{"city":"Klaipėda"},
{"city":"Klang"},
{"city":"Knoxville"},
{"city":"Koblenz"},
{"city":"Kochi"},
{"city":"Kodaira"},
{"city":"Koforidua"},
{"city":"Koga"},
{"city":"Koganei"},
{"city":"Kohat"},
{"city":"Kokubunji"},
{"city":"Kollam"},
{"city":"Komaki"},
{"city":"Komatsu"},
{"city":"Konya"},
{"city":"Kopeisk"},
{"city":"Korhogo"},
{"city":"Koronadal"},
{"city":"Koshigaya"},
{"city":"Koszalin"},
{"city":"Kota"},
{"city":"Kota Bharu"},
{"city":"Kota Kinabalu"},
{"city":"Kotte"},
{"city":"Koudougou"},
{"city":"Kousséri"},
{"city":"Kozan"},
{"city":"Kozhikode"},
{"city":"Košice"},
{"city":"Kragujevac"},
{"city":"Krakova"},
{"city":"Krasnodar"},
{"city":"Krasnojarsk"},
{"city":"Krefeld"},
{"city":"Kryvyi Rih"},
{"city":"Ksar-el-Kebir"},
{"city":"Ktesifon"},
{"city":"Kuala Lumpur"},
{"city":"Kuala Terengganu"},
{"city":"Kuantan"},
{"city":"Kuching"},
{"city":"Kufa"},
{"city":"Kuki"},
{"city":"Kulob"},
{"city":"Kumagaya"},
{"city":"Kumamoto"},
{"city":"Kumasi"},
{"city":"Kumba"},
{"city":"Kunming"},
{"city":"Kuopio"},
{"city":"Kurashiki"},
{"city":"Kure"},
{"city":"Kurgan"},
{"city":"Kurnool"},
{"city":"Kurume"},
{"city":"Kusatsu"},
{"city":"Kushiro"},
{"city":"Kusong"},
{"city":"Kutaisi"},
{"city":"Kuwait"},
{"city":"Kuwana"},
{"city":"Kuşadası"},
{"city":"Kâhta"},
{"city":"Kâmpóng Cham"},
{"city":"Kökşetaw"},
{"city":"Köln"},
{"city":"Kööpenhamina"},
{"city":"Kütahya"},
{"city":"Kırklareli"},
{"city":"Kırıkkale"},
{"city":"Kırşehir"},
{"city":"Kōbe"},
{"city":"Kōchi"},
{"city":"Kōfu"},
{"city":"Kōnosu"},
{"city":"Kōriyama"},
{"city":"L'Hospitalet de Llobregat"},
{"city":"La Ceiba"},
{"city":"La Guaira"},
{"city":"La Paz"},
{"city":"La Plata"},
{"city":"La Rioja"},
{"city":"La Serena"},
{"city":"La Vega"},
{"city":"La Victoria"},
{"city":"Labé"},
{"city":"Lae"},
{"city":"Lafayette"},
{"city":"Lagarto"},
{"city":"Lages"},
{"city":"Lagos"},
{"city":"Lahore"},
{"city":"Lahti"},
{"city":"Laibin"},
{"city":"Laiyang"},
{"city":"Lakeland"},
{"city":"Lakewood"},
{"city":"Lancaster"},
{"city":"Langfang"},
{"city":"Lansing"},
{"city":"Lanzhou"},
{"city":"Lapu-Lapu City"},
{"city":"Laredo"},
{"city":"Larissa"},
{"city":"Larkana"},
{"city":"Las Condes"},
{"city":"Las Cruces"},
{"city":"Las Piñas"},
{"city":"Las Tunas"},
{"city":"Las Vegas"},
{"city":"Lashio"},
{"city":"Lashkar Gah"},
{"city":"Latina"},
{"city":"Lattakia"},
{"city":"Launceston"},
{"city":"Lauro de Freitas"},
{"city":"Lausanne"},
{"city":"Laval"},
{"city":"Lavras"},
{"city":"Le Havre"},
{"city":"Le Mans"},
{"city":"Lee's Summit"},
{"city":"Leeds"},
{"city":"Legazpi"},
{"city":"Leicester"},
{"city":"Leiden"},
{"city":"Leipzig"},
{"city":"Leiria"},
{"city":"Leiyang"},
{"city":"Leizhou"},
{"city":"Leshan"},
{"city":"Leuven"},
{"city":"Leverkusen"},
{"city":"Lewisville"},
{"city":"Lexington"},
{"city":"León"},
{"city":"Lhasa"},
{"city":"Lianjiang"},
{"city":"Lianyuan"},
{"city":"Lianyungang"},
{"city":"Lianzhou"},
{"city":"Liaocheng"},
{"city":"Liaoyang"},
{"city":"Liaoyuan"},
{"city":"Liberec"},
{"city":"Libertad"},
{"city":"Libreville"},
{"city":"Lichinga"},
{"city":"Ligao"},
{"city":"Lijiang"},
{"city":"Likasi"},
{"city":"Liling"},
{"city":"Lille"},
{"city":"Lilongwe"},
{"city":"Lima"},
{"city":"Limassol"},
{"city":"Limeira"},
{"city":"Limoges"},
{"city":"Lincang"},
{"city":"Lincoln"},
{"city":"Linfen"},
{"city":"Linhares"},
{"city":"Linjiang"},
{"city":"Linköping"},
{"city":"Linyi"},
{"city":"Linz"},
{"city":"Lipa"},
{"city":"Lira"},
{"city":"Lishui"},
{"city":"Lissabon"},
{"city":"Little Rock"},
{"city":"Liupanshui"},
{"city":"Liuzhou"},
{"city":"Liverpool"},
{"city":"Livingstone (Sambia)"},
{"city":"Livorno"},
{"city":"Liège"},
{"city":"Ljubljana"},
{"city":"Lobito"},
{"city":"Loja"},
{"city":"Lomas de Zamora"},
{"city":"Lomé"},
{"city":"London"},
{"city":"Londrina"},
{"city":"Long Beach"},
{"city":"Long Xuyên"},
{"city":"Longnan"},
{"city":"Longyan"},
{"city":"Lontoo"},
{"city":"Los Angeles"},
{"city":"Los Mochis"},
{"city":"Los Teques"},
{"city":"Los Ángeles"},
{"city":"Loudi"},
{"city":"Louisville"},
{"city":"Loures"},
{"city":"Lowell"},
{"city":"Lower Hutt"},
{"city":"Luanda"},
{"city":"Luanshya"},
{"city":"Lubango"},
{"city":"Lubbock"},
{"city":"Lublin"},
{"city":"Lubumbashi"},
{"city":"Lucena"},
{"city":"Lucknow"},
{"city":"Ludhiana"},
{"city":"Ludwigshafen am Rhein"},
{"city":"Luena"},
{"city":"Lufeng"},
{"city":"Luohe"},
{"city":"Luoyang"},
{"city":"Lusaka"},
{"city":"Lutsk"},
{"city":"Luxemburg"},
{"city":"Luxor"},
{"city":"Luzhou"},
{"city":"Luziânia"},
{"city":"Lu’an"},
{"city":"Lviv"},
{"city":"Lyon"},
{"city":"Lyypekki"},
{"city":"Länsi-Berliini"},
{"city":"Lévis"},
{"city":"Lüliang"},
{"city":"Maastricht"},
{"city":"Mabalacat"},
{"city":"Macao"},
{"city":"Macapá"},
{"city":"Macaé"},
{"city":"Maceió"},
{"city":"Machakos"},
{"city":"Machala"},
{"city":"Machida"},
{"city":"Machilipatnam"},
{"city":"Machiques"},
{"city":"Macon"},
{"city":"Madison"},
{"city":"Madrid"},
{"city":"Madurai"},
{"city":"Maebashi"},
{"city":"Magdeburg"},
{"city":"Magnitogorsk"},
{"city":"Magé"},
{"city":"Mahatškala"},
{"city":"Mahbubnagar"},
{"city":"Mahendranagar"},
{"city":"Mahiljou"},
{"city":"Maia"},
{"city":"Maiduguri"},
{"city":"Maikop"},
{"city":"Mainz"},
{"city":"Makati"},
{"city":"Makeni"},
{"city":"Makurdi"},
{"city":"Malabo"},
{"city":"Malabon"},
{"city":"Malakal"},
{"city":"Malakka"},
{"city":"Malanje"},
{"city":"Malatya"},
{"city":"Malaybalay"},
{"city":"Malayer"},
{"city":"Malolos"},
{"city":"Malé"},
{"city":"Mamuju"},
{"city":"Managua"},
{"city":"Manama"},
{"city":"Manaus"},
{"city":"Manchester"},
{"city":"Mandalay"},
{"city":"Mandaluyong"},
{"city":"Mandaue"},
{"city":"Mandi Bahauddin"},
{"city":"Mangalore"},
{"city":"Manila"},
{"city":"Manisa"},
{"city":"Mannheim"},
{"city":"Manokwari"},
{"city":"Manp'o"},
{"city":"Mansa"},
{"city":"Manta"},
{"city":"Manzanillo"},
{"city":"Manzhouli"},
{"city":"Manzini"},
{"city":"Maoming"},
{"city":"Maputo"},
{"city":"Mar del Plata"},
{"city":"Marabá"},
{"city":"Maracaibo"},
{"city":"Maracanaú"},
{"city":"Maracay"},
{"city":"Maradi"},
{"city":"Maranguape"},
{"city":"Marawi"},
{"city":"Marbella"},
{"city":"Margilan"},
{"city":"Marikina"},
{"city":"Maringá"},
{"city":"Marituba"},
{"city":"Markham"},
{"city":"Marrakech"},
{"city":"Marsa Matruh"},
{"city":"Marseille"},
{"city":"Marugame"},
{"city":"Mary"},
{"city":"Marília"},
{"city":"Masaya"},
{"city":"Masbate City"},
{"city":"Mascara"},
{"city":"Maseru"},
{"city":"Masqat"},
{"city":"Masvingo"},
{"city":"Matadi"},
{"city":"Matagalpa"},
{"city":"Matamoros"},
{"city":"Matanzas"},
{"city":"Mati"},
{"city":"Matola"},
{"city":"Matosinhos"},
{"city":"Matrah"},
{"city":"Matsubara"},
{"city":"Matsudo"},
{"city":"Matsue"},
{"city":"Matsumoto"},
{"city":"Matsusaka"},
{"city":"Matsuyama"},
{"city":"Maturín"},
{"city":"Mauá"},
{"city":"Maxixe, Mosambik"},
{"city":"Mazar-i-Sharif"},
{"city":"Mazatlán"},
{"city":"Mazyr"},
{"city":"Mašhad"},
{"city":"Ma’anshan"},
{"city":"Mbale"},
{"city":"Mbanza Kongo"},
{"city":"Mbuji-Mayi"},
{"city":"McAllen"},
{"city":"McKinney"},
{"city":"Medellín"},
{"city":"Medina"},
{"city":"Meerut"},
{"city":"Mehsana"},
{"city":"Meishan"},
{"city":"Meizhou"},
{"city":"Mekele"},
{"city":"Mekka"},
{"city":"Meknes"},
{"city":"Melbourne"},
{"city":"Melipilla"},
{"city":"Memphis"},
{"city":"Mendoza"},
{"city":"Menifee"},
{"city":"Merauke"},
{"city":"Merka"},
{"city":"Merlo"},
{"city":"Mersin"},
{"city":"Mesa"},
{"city":"Mesquita"},
{"city":"Mesquite"},
{"city":"Messina"},
{"city":"Metz"},
{"city":"Mexicali"},
{"city":"Meycauayan"},
{"city":"Miami"},
{"city":"Miami Gardens"},
{"city":"Mianyang"},
{"city":"Middlesbrough"},
{"city":"Midland"},
{"city":"Milagro"},
{"city":"Milano"},
{"city":"Milton Keynes"},
{"city":"Milwaukee"},
{"city":"Minatitlán"},
{"city":"Mingora"},
{"city":"Minna"},
{"city":"Minneapolis"},
{"city":"Minsk"},
{"city":"Minuf"},
{"city":"Minya"},
{"city":"Minō"},
{"city":"Mira-Bhayandar"},
{"city":"Miramar"},
{"city":"Miri"},
{"city":"Mirpur"},
{"city":"Mirpur Khas"},
{"city":"Misato"},
{"city":"Mishima"},
{"city":"Miskolc"},
{"city":"Mississauga"},
{"city":"Mitaka"},
{"city":"Mito"},
{"city":"Miyakonojō"},
{"city":"Miyazaki"},
{"city":"Mobile"},
{"city":"Modena"},
{"city":"Modesto"},
{"city":"Moers"},
{"city":"Mogadishu"},
{"city":"Mogi Guaçu"},
{"city":"Mogi das Cruzes"},
{"city":"Mohammedia"},
{"city":"Mokpo"},
{"city":"Mombasa"},
{"city":"Monastir"},
{"city":"Mongu"},
{"city":"Monrovia"},
{"city":"Monte Grande"},
{"city":"Montego Bay"},
{"city":"Montero"},
{"city":"Monterrey"},
{"city":"Montería"},
{"city":"Montes Claros"},
{"city":"Montevideo"},
{"city":"Montgomery"},
{"city":"Montpellier"},
{"city":"Montreal"},
{"city":"Montreuil"},
{"city":"Monywa"},
{"city":"Monza"},
{"city":"Moradabad"},
{"city":"Moreno"},
{"city":"Moreno Valley"},
{"city":"Moriguchi"},
{"city":"Morioka"},
{"city":"Morogoro"},
{"city":"Moshi"},
{"city":"Moskova"},
{"city":"Mossoró"},
{"city":"Mostaganem"},
{"city":"Mosul"},
{"city":"Moundou"},
{"city":"Mudanjiang"},
{"city":"Mufulira"},
{"city":"Mulhouse"},
{"city":"Multan"},
{"city":"Mumbai"},
{"city":"Munchon"},
{"city":"Muntinlupa"},
{"city":"Murfreesboro"},
{"city":"Muriaé"},
{"city":"Murom"},
{"city":"Murrieta"},
{"city":"Musashino"},
{"city":"Musoma"},
{"city":"Mutare"},
{"city":"Muzaffargarh"},
{"city":"Muzaffarnagar"},
{"city":"Muzaffarpur"},
{"city":"Muş"},
{"city":"Mwanza"},
{"city":"Myeik"},
{"city":"Myitkyina"},
{"city":"Mytištši"},
{"city":"Mzuzu"},
{"city":"Médéa"},
{"city":"Mérida"},
{"city":"México"},
{"city":"Móstoles"},
{"city":"Mönchengladbach"},
{"city":"Mörön"},
{"city":"Mülheim an der Ruhr"},
{"city":"München"},
{"city":"Münster"},
{"city":"N'dalatando"},
{"city":"Nabatîyé"},
{"city":"Naberežnyje Tšelny"},
{"city":"Nablus"},
{"city":"Nacala"},
{"city":"Nador"},
{"city":"Naga"},
{"city":"Nagahama"},
{"city":"Nagano"},
{"city":"Nagaoka"},
{"city":"Nagareyama"},
{"city":"Nagasaki"},
{"city":"Nagoya"},
{"city":"Nagpur"},
{"city":"Nagqu"},
{"city":"Naha"},
{"city":"Nairobi"},
{"city":"Najaf"},
{"city":"Najafabad"},
{"city":"Najran"},
{"city":"Nakhon Ratchasima"},
{"city":"Nakhon Si Thammarat"},
{"city":"Nakuru"},
{"city":"Nam Định"},
{"city":"Namangan"},
{"city":"Namibe"},
{"city":"Namp'o"},
{"city":"Nampa"},
{"city":"Nampula"},
{"city":"Namur"},
{"city":"Namyangju"},
{"city":"Nanchang"},
{"city":"Nanchong"},
{"city":"Nancy"},
{"city":"Nanjing"},
{"city":"Nanning"},
{"city":"Nanping"},
{"city":"Nantes"},
{"city":"Nantong"},
{"city":"Nanyang"},
{"city":"Naperville"},
{"city":"Napoli"},
{"city":"Nara"},
{"city":"Narashino"},
{"city":"Narita"},
{"city":"Nashik"},
{"city":"Nashville"},
{"city":"Nasiriyya"},
{"city":"Nassau"},
{"city":"Nasushiobara"},
{"city":"Natal"},
{"city":"Navi Mumbai"},
{"city":"Navoi"},
{"city":"Navotas"},
{"city":"Naypyidaw"},
{"city":"Nazarabad"},
{"city":"Nazilli"},
{"city":"Ndola"},
{"city":"Neftejugansk"},
{"city":"Neftekamsk"},
{"city":"Negombo"},
{"city":"Neijiang"},
{"city":"Neiva"},
{"city":"Nellore"},
{"city":"Netanya"},
{"city":"Neuquén"},
{"city":"Neuss"},
{"city":"Nevinnomyssk"},
{"city":"Nevşehir"},
{"city":"New Bedford"},
{"city":"New Cairo"},
{"city":"New Delhi"},
{"city":"New Haven"},
{"city":"New Orleans"},
{"city":"New York"},
{"city":"Newark"},
{"city":"Newcastle"},
{"city":"Newcastle upon Tyne"},
{"city":"Newport"},
{"city":"Newport News"},
{"city":"Neyagawa"},
{"city":"Nešabur"},
{"city":"Ngaoundéré"},
{"city":"Nha Trang"},
{"city":"Niamey"},
{"city":"Niigata"},
{"city":"Niihama"},
{"city":"Niiza"},
{"city":"Nikopol"},
{"city":"Nikosia"},
{"city":"Nilópolis"},
{"city":"Ningbo"},
{"city":"Ningde"},
{"city":"Ningxiang"},
{"city":"Nishinomiya"},
{"city":"Nishio"},
{"city":"Nishitōkyō"},
{"city":"Nisibis"},
{"city":"Niterói"},
{"city":"Nizamabad"},
{"city":"Nizza"},
{"city":"Niğde"},
{"city":"Niš"},
{"city":"Nižnekamsk"},
{"city":"Nižnevartovsk"},
{"city":"Nižni Novgorod"},
{"city":"Nižni Tagil"},
{"city":"Nkayi"},
{"city":"Nobeoka"},
{"city":"Noda"},
{"city":"Nogales"},
{"city":"Noida"},
{"city":"Nojabrsk"},
{"city":"Nonsan"},
{"city":"Nonthaburi"},
{"city":"Norfolk"},
{"city":"Norman"},
{"city":"North Charleston"},
{"city":"North Las Vegas"},
{"city":"Norwalk"},
{"city":"Norwich"},
{"city":"Nossa Senhora do Socorro"},
{"city":"Nottingham"},
{"city":"Nouadhibou"},
{"city":"Nouakchott"},
{"city":"Nova Friburgo"},
{"city":"Nova Iguaçu"},
{"city":"Novara"},
{"city":"Novgorod"},
{"city":"Novi Sad"},
{"city":"Novo Hamburgo"},
{"city":"Novokuibyševsk"},
{"city":"Novomoskovsk"},
{"city":"Novorossijsk"},
{"city":"Novosibirsk"},
{"city":"Novotšeboksarsk"},
{"city":"Novotšerkassk"},
{"city":"Novošahtinsk"},
{"city":"Novyi Urengoi"},
{"city":"Nowshera, Khyber Pakhtunkhwa"},
{"city":"Nukus"},
{"city":"Numazu"},
{"city":"Nyala"},
{"city":"Nyingchi"},
{"city":"Nyíregyháza"},
{"city":"Nîmes"},
{"city":"Nürnberg"},
{"city":"N’Djamena"},
{"city":"Oakland"},
{"city":"Oberhausen"},
{"city":"Obihiro"},
{"city":"Obninsk"},
{"city":"Obuasi"},
{"city":"Oceanside"},
{"city":"Ocumare del Tuy"},
{"city":"Odawara"},
{"city":"Odense"},
{"city":"Odessa"},
{"city":"Odivelas"},
{"city":"Offenbach am Main"},
{"city":"Ogbomosho"},
{"city":"Okara, Pakistan"},
{"city":"Okayama"},
{"city":"Okazaki"},
{"city":"Okinawa"},
{"city":"Oklahoma City"},
{"city":"Oktjabrski"},
{"city":"Olathe"},
{"city":"Oldenburg"},
{"city":"Olinda"},
{"city":"Olomouc"},
{"city":"Olongapo"},
{"city":"Olsztyn"},
{"city":"Omaha"},
{"city":"Omdurman"},
{"city":"Omsk"},
{"city":"Ondjiva"},
{"city":"Ongole"},
{"city":"Onitsha"},
{"city":"Onomichi"},
{"city":"Ontario"},
{"city":"Opole"},
{"city":"Oradea"},
{"city":"Oran"},
{"city":"Orange"},
{"city":"Ordos"},
{"city":"Orenburg"},
{"city":"Orlando"},
{"city":"Orléans"},
{"city":"Ormoc"},
{"city":"Orsk"},
{"city":"Oruro"},
{"city":"Osaka"},
{"city":"Osan"},
{"city":"Osasco"},
{"city":"Oshawa"},
{"city":"Oslo"},
{"city":"Osmaniye"},
{"city":"Osnabrück"},
{"city":"Osogbo"},
{"city":"Osorno"},
{"city":"Ostrava"},
{"city":"Otaru"},
{"city":"Ottawa"},
{"city":"Ouagadougou"},
{"city":"Ouahigouya"},
{"city":"Ouargla"},
{"city":"Oujda"},
{"city":"Oulu"},
{"city":"Oumé"},
{"city":"Ourinhos"},
{"city":"Overland Park"},
{"city":"Owerri"},
{"city":"Owo, Nigeria"},
{"city":"Oxford"},
{"city":"Oxnard"},
{"city":"Oyama"},
{"city":"Oyo"},
{"city":"Ozamiz"},
{"city":"Oš"},
{"city":"P'yŏngsŏng"},
{"city":"Paderborn"},
{"city":"Padova"},
{"city":"Pagadian"},
{"city":"Paita"},
{"city":"Paju"},
{"city":"Pakpattan"},
{"city":"Pakse"},
{"city":"Palakkad"},
{"city":"Palermo"},
{"city":"Palhoça"},
{"city":"Pali"},
{"city":"Palm Bay"},
{"city":"Palma"},
{"city":"Palma Soriano"},
{"city":"Palmas"},
{"city":"Palmdale"},
{"city":"Panabo"},
{"city":"Panamá"},
{"city":"Panjin"},
{"city":"Panzhihua"},
{"city":"Paramaribo"},
{"city":"Paranaguá"},
{"city":"Paraná"},
{"city":"Parauapebas"},
{"city":"Parañaque"},
{"city":"Pariisi"},
{"city":"Parma"},
{"city":"Parnamirim"},
{"city":"Parnaíba"},
{"city":"Pasadena"},
{"city":"Pasay"},
{"city":"Pasig"},
{"city":"Passo Fundo"},
{"city":"Passos, Minas Gerais"},
{"city":"Pasto"},
{"city":"Patan"},
{"city":"Paterson"},
{"city":"Pathankot"},
{"city":"Pathein"},
{"city":"Patiala"},
{"city":"Patna"},
{"city":"Patnos"},
{"city":"Patos"},
{"city":"Patos de Minas"},
{"city":"Patras"},
{"city":"Pattaya"},
{"city":"Paulista"},
{"city":"Paulo Afonso"},
{"city":"Pavlodar"},
{"city":"Paço do Lumiar"},
{"city":"Pearland"},
{"city":"Pedro Juan Caballero"},
{"city":"Peking"},
{"city":"Pelotas"},
{"city":"Pemba"},
{"city":"Pembroke Pines"},
{"city":"Penza"},
{"city":"Peoria"},
{"city":"Pereira"},
{"city":"Peristeri"},
{"city":"Perm"},
{"city":"Perpignan"},
{"city":"Perth"},
{"city":"Perugia"},
{"city":"Pervouralsk"},
{"city":"Pescara"},
{"city":"Peshawar"},
{"city":"Petah Tikva"},
{"city":"Petaling Jaya"},
{"city":"Peterborough"},
{"city":"Petrolina"},
{"city":"Petropavl"},
{"city":"Petroskoi"},
{"city":"Petrópolis"},
{"city":"Pforzheim"},
{"city":"Phan Thiết"},
{"city":"Philadelphia"},
{"city":"Phnom Penh"},
{"city":"Phoenix"},
{"city":"Phrae"},
{"city":"Piacenza"},
{"city":"Piedras Negras"},
{"city":"Pietari"},
{"city":"Pihkova"},
{"city":"Pikine"},
{"city":"Pimpri-Chinchwad"},
{"city":"Pinar del Río"},
{"city":"Pindamonhangaba"},
{"city":"Pingdingshan"},
{"city":"Pingdu"},
{"city":"Pingliang"},
{"city":"Pingxiang"},
{"city":"Pinhais"},
{"city":"Pinsk"},
{"city":"Piracicaba"},
{"city":"Piranshahr"},
{"city":"Pireus"},
{"city":"Pisco"},
{"city":"Pitești"},
{"city":"Pittsburgh"},
{"city":"Piura"},
{"city":"Pizhou"},
{"city":"Pjongjang"},
{"city":"Plano"},
{"city":"Playa del Carmen"},
{"city":"Pleiku"},
{"city":"Pleven"},
{"city":"Ploiești"},
{"city":"Plovdiv"},
{"city":"Plymouth"},
{"city":"Plzeň"},
{"city":"Pocheon"},
{"city":"Podgorica"},
{"city":"Pohang"},
{"city":"Pohjois-Khartum"},
{"city":"Pointe-Noire"},
{"city":"Pokhara"},
{"city":"Pol-e Khomri"},
{"city":"Polatlı"},
{"city":"Pomona"},
{"city":"Pompano Beach"},
{"city":"Ponce"},
{"city":"Ponta Grossa"},
{"city":"Popayán"},
{"city":"Porlamar"},
{"city":"Port Blair"},
{"city":"Port Harcourt"},
{"city":"Port Louis"},
{"city":"Port Moresby"},
{"city":"Port Said"},
{"city":"Port St. Lucie"},
{"city":"Port Sudan"},
{"city":"Port-Gentil"},
{"city":"Port-au-Prince"},
{"city":"Port-de-Paix"},
{"city":"Portland"},
{"city":"Portmore"},
{"city":"Porto"},
{"city":"Porto Alegre"},
{"city":"Porto Amboim"},
{"city":"Porto Seguro"},
{"city":"Porto Velho"},
{"city":"Porto-Novo"},
{"city":"Portoviejo"},
{"city":"Portsmouth"},
{"city":"Posadas"},
{"city":"Potchefstroom"},
{"city":"Potosí"},
{"city":"Potsdam"},
{"city":"Pouso Alegre"},
{"city":"Poznań"},
{"city":"Poá"},
{"city":"Poços de Caldas"},
{"city":"Praha"},
{"city":"Praia"},
{"city":"Praia Grande"},
{"city":"Prato"},
{"city":"Prayagraj"},
{"city":"Presidente Prudente"},
{"city":"Preston"},
{"city":"Pretoria"},
{"city":"Pristina"},
{"city":"Prizren"},
{"city":"Providence"},
{"city":"Provo"},
{"city":"Pu'er"},
{"city":"Pucallpa"},
{"city":"Pudong"},
{"city":"Puebla de Zaragoza"},
{"city":"Pueblo"},
{"city":"Puente Alto"},
{"city":"Puerto Barrios"},
{"city":"Puerto Cabello"},
{"city":"Puerto Madryn"},
{"city":"Puerto Montt"},
{"city":"Puerto Princesa"},
{"city":"Puerto Vallarta"},
{"city":"Puerto la Cruz"},
{"city":"Pune"},
{"city":"Puning"},
{"city":"Puno"},
{"city":"Punta Arenas"},
{"city":"Punto Fijo"},
{"city":"Puri"},
{"city":"Purnia"},
{"city":"Purwokerto"},
{"city":"Putian"},
{"city":"Puyang"},
{"city":"Pyeongtaek"},
{"city":"Pécs"},
{"city":"Pétion-Ville"},
{"city":"Płock"},
{"city":"Qaem Shahr"},
{"city":"Qamdo"},
{"city":"Qarši"},
{"city":"Qazvin"},
{"city":"Qina"},
{"city":"Qingdao"},
{"city":"Qingyang"},
{"city":"Qingyuan"},
{"city":"Qinhuangdao"},
{"city":"Qinzhou"},
{"city":"Qiqihar"},
{"city":"Qitaihe"},
{"city":"Qom"},
{"city":"Qostanay"},
{"city":"Quanzhou"},
{"city":"Quebec"},
{"city":"Queimados"},
{"city":"Quelimane"},
{"city":"Quetta"},
{"city":"Quetzaltenango"},
{"city":"Quevedo"},
{"city":"Quezon City"},
{"city":"Qui Nhon"},
{"city":"Quibdó"},
{"city":"Quillacollo"},
{"city":"Quilmes"},
{"city":"Quilpué"},
{"city":"Quincy"},
{"city":"Quito"},
{"city":"Qujing"},
{"city":"Quzhou"},
{"city":"Quíbor"},
{"city":"Quảng Ngãi"},
{"city":"Qızılorda"},
{"city":"Rabat"},
{"city":"Radom"},
{"city":"Rafael Castillo"},
{"city":"Rafah"},
{"city":"Rahim Yar Khan"},
{"city":"Raipur"},
{"city":"Rajahmundry"},
{"city":"Rajkot"},
{"city":"Rajshahi"},
{"city":"Raleigh"},
{"city":"Ramadi"},
{"city":"Ramat Gan"},
{"city":"Ramos Mejía"},
{"city":"Rancagua"},
{"city":"Ranchi"},
{"city":"Rancho Cucamonga"},
{"city":"Randburg"},
{"city":"Raqqa"},
{"city":"Rasŏn"},
{"city":"Ravenna"},
{"city":"Rawalpindi"},
{"city":"Ray"},
{"city":"Rašt"},
{"city":"Recife"},
{"city":"Recklinghausen"},
{"city":"Red Deer"},
{"city":"Regensburg"},
{"city":"Reggio di Calabria"},
{"city":"Reggio nell’Emilia"},
{"city":"Regina"},
{"city":"Rehovot"},
{"city":"Reims"},
{"city":"Remscheid"},
{"city":"Rennes"},
{"city":"Reno"},
{"city":"Renton"},
{"city":"Resende"},
{"city":"Resistencia"},
{"city":"Reutlingen"},
{"city":"Reykjavík"},
{"city":"Reynosa"},
{"city":"Riad"},
{"city":"Rialto"},
{"city":"Ribeirão Pires"},
{"city":"Ribeirão Preto"},
{"city":"Richmond"},
{"city":"Richmond Hill"},
{"city":"Richmond, California"},
{"city":"Riika"},
{"city":"Rijeka"},
{"city":"Rimini"},
{"city":"Rio Branco"},
{"city":"Rio Claro"},
{"city":"Rio Grande, Rio Grande do Sul"},
{"city":"Rio Rancho (New Mexico)"},
{"city":"Rio Verde"},
{"city":"Rio das Ostras"},
{"city":"Rio de Janeiro"},
{"city":"Riobamba"},
{"city":"Riohacha"},
{"city":"Rishon LeZion"},
{"city":"Riverside"},
{"city":"Rize"},
{"city":"Rizhao"},
{"city":"Rjazan"},
{"city":"Roanoke"},
{"city":"Rochester"},
{"city":"Rockford"},
{"city":"Rodos"},
{"city":"Rohtak"},
{"city":"Rondonópolis"},
{"city":"Roodepoort"},
{"city":"Rooma"},
{"city":"Rosario"},
{"city":"Rosetta"},
{"city":"Roseville"},
{"city":"Rostock"},
{"city":"Rotherham"},
{"city":"Rotterdam"},
{"city":"Rouen"},
{"city":"Round Rock"},
{"city":"Rubtsovsk"},
{"city":"Ruda Śląska"},
{"city":"Rudniy"},
{"city":"Rufisque"},
{"city":"Ruili"},
{"city":"Ruse"},
{"city":"Rustavi"},
{"city":"Rybinsk"},
{"city":"Rybnik"},
{"city":"Rzeszów"},
{"city":"Río Cuarto"},
{"city":"Sa Đéc"},
{"city":"Saarbrücken"},
{"city":"Sabadell"},
{"city":"Sabará"},
{"city":"Sabratha"},
{"city":"Sabzevar"},
{"city":"Sacaba"},
{"city":"Sacheon"},
{"city":"Sacramento"},
{"city":"Safi"},
{"city":"Saga"},
{"city":"Sagamihara"},
{"city":"Sagay"},
{"city":"Saguenay"},
{"city":"Saharanpur"},
{"city":"Sahiwal"},
{"city":"Saijō"},
{"city":"Saint Paul"},
{"city":"Saint-Denis"},
{"city":"Saint-Denis de la Réunion"},
{"city":"Saint-Louis"},
{"city":"Saint-Marc"},
{"city":"Saint-Paul"},
{"city":"Saint-Étienne"},
{"city":"Saitama"},
{"city":"Sakado"},
{"city":"Sakai"},
{"city":"Sakaka"},
{"city":"Sakura"},
{"city":"Salala"},
{"city":"Salamiyya"},
{"city":"Salavat"},
{"city":"Salem"},
{"city":"Salerno"},
{"city":"Salford"},
{"city":"Salinas"},
{"city":"Salt Lake City"},
{"city":"Salta"},
{"city":"Saltillo"},
{"city":"Salto"},
{"city":"Salvador"},
{"city":"Salzburg"},
{"city":"Salzgitter"},
{"city":"Salé"},
{"city":"Samal"},
{"city":"Samandağ"},
{"city":"Samara"},
{"city":"Samarinda"},
{"city":"Samarkand"},
{"city":"Samarra"},
{"city":"Samawa"},
{"city":"Samsun"},
{"city":"San Antonio"},
{"city":"San Bernardino"},
{"city":"San Bernardo"},
{"city":"San Carlos"},
{"city":"San Carlos de Bariloche"},
{"city":"San Cristóbal"},
{"city":"San Cristóbal de las Casas"},
{"city":"San Diego"},
{"city":"San Felipe"},
{"city":"San Fernando"},
{"city":"San Fernando de Apure"},
{"city":"San Francisco"},
{"city":"San Francisco de Macorís"},
{"city":"San Jose"},
{"city":"San Jose del Monte"},
{"city":"San José"},
{"city":"San Juan"},
{"city":"San Justo"},
{"city":"San Lorenzo"},
{"city":"San Luis"},
{"city":"San Luis Potosí"},
{"city":"San Luis Río Colorado"},
{"city":"San Mateo"},
{"city":"San Miguel"},
{"city":"San Miguel de Tucumán"},
{"city":"San Nicolás de los Arroyos"},
{"city":"San Pablo"},
{"city":"San Pedro"},
{"city":"San Pedro Sula"},
{"city":"San Pedro de Macorís"},
{"city":"San Pedro de la Paz"},
{"city":"San Rafael"},
{"city":"San Salvador"},
{"city":"San Salvador de Jujuy"},
{"city":"Sanaa"},
{"city":"Sanandaj"},
{"city":"Sancti Spíritus"},
{"city":"Sanda"},
{"city":"Sandakan"},
{"city":"Sandvika"},
{"city":"Sandy Springs"},
{"city":"Sangju"},
{"city":"Sangli"},
{"city":"Sanmenxia"},
{"city":"Sanming"},
{"city":"Sano"},
{"city":"Sansibar"},
{"city":"Santa Ana"},
{"city":"Santa Bárbara d'Oeste"},
{"city":"Santa Clara"},
{"city":"Santa Clarita"},
{"city":"Santa Cruz de la Sierra"},
{"city":"Santa Cruz do Sul"},
{"city":"Santa Fe"},
{"city":"Santa Lucía"},
{"city":"Santa Luzia, Minas Gerais"},
{"city":"Santa Maria"},
{"city":"Santa Maria da Feira"},
{"city":"Santa Marta"},
{"city":"Santa Rita, Paraíba"},
{"city":"Santa Rita, Venezuela"},
{"city":"Santa Rosa"},
{"city":"Santa Tecla"},
{"city":"Santana"},
{"city":"Santana de Parnaíba"},
{"city":"Santarém"},
{"city":"Santiago"},
{"city":"Santiago de Chile"},
{"city":"Santiago de Cuba"},
{"city":"Santiago de Querétaro"},
{"city":"Santiago de los Caballeros"},
{"city":"Santiago del Estero"},
{"city":"Santo André"},
{"city":"Santo Antônio de Jesus"},
{"city":"Santo Domingo"},
{"city":"Santos"},
{"city":"Sanya"},
{"city":"Sapporo"},
{"city":"Sapucaia do Sul"},
{"city":"Saqqez"},
{"city":"Sarajevo"},
{"city":"Saransk"},
{"city":"Saratov"},
{"city":"Sargodha"},
{"city":"Sarh"},
{"city":"Sari"},
{"city":"Sariwŏn"},
{"city":"Sasebo"},
{"city":"Saskatoon"},
{"city":"Sassari"},
{"city":"Satara"},
{"city":"Savannah"},
{"city":"Savannakhet"},
{"city":"Sayama"},
{"city":"Say’un"},
{"city":"Scottsdale"},
{"city":"Seattle"},
{"city":"Seeb"},
{"city":"Seixal"},
{"city":"Sejong"},
{"city":"Sekondi-Takoradi"},
{"city":"Semey"},
{"city":"Semnan"},
{"city":"Sendai"},
{"city":"Seogwipo"},
{"city":"Seongnam"},
{"city":"Seosan"},
{"city":"Seremban"},
{"city":"Sergijev Posad"},
{"city":"Serra, Espírito Santo"},
{"city":"Sertãozinho"},
{"city":"Sete Lagoas"},
{"city":"Seto"},
{"city":"Settat"},
{"city":"Setúbal"},
{"city":"Sevastopol"},
{"city":"Seversk"},
{"city":"Shah Alam"},
{"city":"Shanghai"},
{"city":"Shangluo"},
{"city":"Shangqiu"},
{"city":"Shangrao"},
{"city":"Shannan"},
{"city":"Shantou"},
{"city":"Shanwei"},
{"city":"Shaoguan"},
{"city":"Shaoxing"},
{"city":"Shaoyang"},
{"city":"Sheberghan"},
{"city":"Sheffield"},
{"city":"Sheikhupura"},
{"city":"Shenyang"},
{"city":"Shenzhen"},
{"city":"Sherbrooke"},
{"city":"Shihezi"},
{"city":"Shijiazhuang"},
{"city":"Shillong"},
{"city":"Shimla"},
{"city":"Shimonoseki"},
{"city":"Shinyanga"},
{"city":"Shiyan"},
{"city":"Shizuishan"},
{"city":"Shizuoka"},
{"city":"Shkodër"},
{"city":"Sholapur"},
{"city":"Shouguang"},
{"city":"Shreveport"},
{"city":"Shuangyashan"},
{"city":"Shuozhou"},
{"city":"Shūnan"},
{"city":"Sialkot"},
{"city":"Sibiu"},
{"city":"Sibu"},
{"city":"Sidi Bel Abbès"},
{"city":"Sidon"},
{"city":"Siegen"},
{"city":"Siguiri"},
{"city":"Siheung"},
{"city":"Siirt"},
{"city":"Sikasso"},
{"city":"Silay"},
{"city":"Siliguri"},
{"city":"Simferopol"},
{"city":"Simi Valley"},
{"city":"Simões Filho"},
{"city":"Sincelejo"},
{"city":"Singapore"},
{"city":"Singida"},
{"city":"Sinop"},
{"city":"Sinpo"},
{"city":"Sinŭiju"},
{"city":"Sioux Falls"},
{"city":"Siping"},
{"city":"Sirjan"},
{"city":"Sittwe"},
{"city":"Sivas"},
{"city":"Siĕm Réab"},
{"city":"Skikda"},
{"city":"Skopje"},
{"city":"Sliven"},
{"city":"Slough"},
{"city":"Smolensk"},
{"city":"Sobral"},
{"city":"Sofia"},
{"city":"Sohag"},
{"city":"Sokodé"},
{"city":"Sokoto"},
{"city":"Solihull"},
{"city":"Solingen"},
{"city":"Soma, Manisa"},
{"city":"Songrim"},
{"city":"Songyuan"},
{"city":"Sorocaba"},
{"city":"Sorsogon City"},
{"city":"Sosnowiec"},
{"city":"Soul"},
{"city":"South Bend"},
{"city":"South Fulton"},
{"city":"Southampton"},
{"city":"Southend-on-Sea"},
{"city":"Soweto"},
{"city":"Spanish Town"},
{"city":"Sparks"},
{"city":"Split"},
{"city":"Spokane"},
{"city":"Springfield"},
{"city":"Srikakulam"},
{"city":"Srinagar"},
{"city":"St Helens"},
{"city":"St. Catharines"},
{"city":"St. John’s"},
{"city":"St. Louis"},
{"city":"St. Petersburg"},
{"city":"Stamford"},
{"city":"Stara Zagora"},
{"city":"Staryi Oskol"},
{"city":"Stavropol"},
{"city":"Sterlitamak"},
{"city":"Stockton"},
{"city":"Stoke-on-Trent"},
{"city":"Strasbourg"},
{"city":"Stuttgart"},
{"city":"Subotica"},
{"city":"Sucre"},
{"city":"Suez"},
{"city":"Suihua"},
{"city":"Suining"},
{"city":"Suita"},
{"city":"Suizhou"},
{"city":"Sukkur"},
{"city":"Sulaimaniyya"},
{"city":"Sullana"},
{"city":"Sumaré"},
{"city":"Sumbawanga"},
{"city":"Sumbe"},
{"city":"Sumqayıt"},
{"city":"Suncheon"},
{"city":"Sunchon"},
{"city":"Sunderland"},
{"city":"Sunnyvale"},
{"city":"Suqian"},
{"city":"Sur"},
{"city":"Surat"},
{"city":"Surat Thani"},
{"city":"Surgut"},
{"city":"Surigao City"},
{"city":"Surprise"},
{"city":"Surrey"},
{"city":"Suwon"},
{"city":"Suzano"},
{"city":"Suzhou"},
{"city":"Suzuka"},
{"city":"Swabi"},
{"city":"Swansea"},
{"city":"Swindon"},
{"city":"Sydney"},
{"city":"Syktyvkar"},
{"city":"Sylhet"},
{"city":"Syracuse"},
{"city":"Syrakusa"},
{"city":"Szczecin"},
{"city":"Szeged"},
{"city":"São Bernardo do Campo"},
{"city":"São Caetano do Sul"},
{"city":"São Carlos"},
{"city":"São Gonçalo"},
{"city":"São José de Ribamar"},
{"city":"São José do Rio Preto"},
{"city":"São José dos Campos"},
{"city":"São José dos Pinhais"},
{"city":"São José, Santa Catarina"},
{"city":"São João de Meriti"},
{"city":"São Leopoldo"},
{"city":"São Lourenço da Mata"},
{"city":"São Luís"},
{"city":"São Mateus, Espírito Santo"},
{"city":"São Paulo"},
{"city":"São Vicente, São Paulo"},
{"city":"Ségou"},
{"city":"Sétif"},
{"city":"Sōka"},
{"city":"Ta'izz"},
{"city":"Tabaco"},
{"city":"Tabora"},
{"city":"Taboão da Serra"},
{"city":"Tabrīz"},
{"city":"Tabuk"},
{"city":"Tabuk, Saudi Arabia"},
{"city":"Tacheng"},
{"city":"Tachikawa"},
{"city":"Tacloban"},
{"city":"Tacna"},
{"city":"Tacoma"},
{"city":"Tacurong"},
{"city":"Taganrog"},
{"city":"Tagbilaran"},
{"city":"Taguig"},
{"city":"Tagum"},
{"city":"Taichung"},
{"city":"Taif"},
{"city":"Tainan"},
{"city":"Taipei"},
{"city":"Taiyuan"},
{"city":"Taizhou"},
{"city":"Tai’an"},
{"city":"Tajimi"},
{"city":"Takamatsu"},
{"city":"Takaoka"},
{"city":"Takarazuka"},
{"city":"Takasaki"},
{"city":"Takatsuki"},
{"city":"Talara"},
{"city":"Talca"},
{"city":"Talcahuano"},
{"city":"Taldyqorghan"},
{"city":"Talisay"},
{"city":"Tallahassee"},
{"city":"Tallinna"},
{"city":"Taloqan"},
{"city":"Tama"},
{"city":"Tamale"},
{"city":"Tambov"},
{"city":"Tampa"},
{"city":"Tampere"},
{"city":"Tanauan"},
{"city":"Tanch'ŏn"},
{"city":"Tandil"},
{"city":"Tanga"},
{"city":"Tanger"},
{"city":"Tangshan"},
{"city":"Tanta"},
{"city":"Taourirt"},
{"city":"Taoyuan"},
{"city":"Taoyuan City"},
{"city":"Tapachula"},
{"city":"Taranto"},
{"city":"Tarapoto"},
{"city":"Taraz"},
{"city":"Tarija"},
{"city":"Tarim (Jemen)"},
{"city":"Tarlac"},
{"city":"Tarnów"},
{"city":"Tarsos"},
{"city":"Tatuí"},
{"city":"Taubaté"},
{"city":"Taunggyi"},
{"city":"Tauranga"},
{"city":"Tawau"},
{"city":"Tayabas"},
{"city":"Taza"},
{"city":"Taškent"},
{"city":"Tbilisi"},
{"city":"Tegucigalpa"},
{"city":"Teheran"},
{"city":"Teixeira de Freitas"},
{"city":"Tekirdağ"},
{"city":"Tel Aviv"},
{"city":"Telford"},
{"city":"Tema"},
{"city":"Temara"},
{"city":"Temecula"},
{"city":"Temirtaw"},
{"city":"Tempe"},
{"city":"Temperley"},
{"city":"Temuco"},
{"city":"Tengzhou"},
{"city":"Tenochtitlán"},
{"city":"Tepic"},
{"city":"Teresina"},
{"city":"Termez"},
{"city":"Terni"},
{"city":"Tete"},
{"city":"Teófilo Otoni"},
{"city":"Thane"},
{"city":"Thanh Hóa"},
{"city":"Thanjavur"},
{"city":"Thessaloniki"},
{"city":"Thimphu"},
{"city":"Thiruvananthapuram"},
{"city":"Thornton"},
{"city":"Thousand Oaks"},
{"city":"Thrissur"},
{"city":"Thunder Bay"},
{"city":"Thái Bình"},
{"city":"Thái Nguyên"},
{"city":"Tianjin"},
{"city":"Tianshui"},
{"city":"Tiaret"},
{"city":"Tieli"},
{"city":"Tieling"},
{"city":"Tijuana"},
{"city":"Tikrit"},
{"city":"Tilburg"},
{"city":"Timișoara"},
{"city":"Timon"},
{"city":"Tinaquillo"},
{"city":"Tirana"},
{"city":"Tiraspol"},
{"city":"Tiruchirapalli"},
{"city":"Tirunelveli"},
{"city":"Tirupati"},
{"city":"Tjumen"},
{"city":"Tlemcen"},
{"city":"Toamasina"},
{"city":"Tobruk"},
{"city":"Tochigi"},
{"city":"Tocuyito"},
{"city":"Toda"},
{"city":"Tokat"},
{"city":"Tokchon"},
{"city":"Tokio"},
{"city":"Tokorozawa"},
{"city":"Tokushima"},
{"city":"Toledo"},
{"city":"Toluca"},
{"city":"Tomakomai"},
{"city":"Tomsk"},
{"city":"Tondabayashi"},
{"city":"Tongchuan"},
{"city":"Tonghua"},
{"city":"Tongi"},
{"city":"Tongliao"},
{"city":"Tongling"},
{"city":"Tongren"},
{"city":"Tongyeong"},
{"city":"Toowoomba"},
{"city":"Topeka"},
{"city":"Torbat-e Heydarieh"},
{"city":"Toride"},
{"city":"Torino"},
{"city":"Toronto"},
{"city":"Torrance"},
{"city":"Torreón"},
{"city":"Toruń"},
{"city":"Tottori"},
{"city":"Touba, Senegal"},
{"city":"Touggourt"},
{"city":"Toulon"},
{"city":"Toulouse"},
{"city":"Tours"},
{"city":"Townsville"},
{"city":"Toyama"},
{"city":"Toyohashi"},
{"city":"Toyokawa"},
{"city":"Toyonaka"},
{"city":"Toyota"},
{"city":"Trabzon"},
{"city":"Trece Martires"},
{"city":"Trier"},
{"city":"Trieste"},
{"city":"Triesten vapaa-alue"},
{"city":"Trindade"},
{"city":"Trinidad"},
{"city":"Tripoli"},
{"city":"Trois-Rivières"},
{"city":"Trondheim"},
{"city":"Trujillo"},
{"city":"Três Lagoas"},
{"city":"Tsu"},
{"city":"Tsuchiura"},
{"city":"Tsukuba"},
{"city":"Tsuruoka"},
{"city":"Tubarão"},
{"city":"Tucson"},
{"city":"Tuguegarao"},
{"city":"Tukholma"},
{"city":"Tula"},
{"city":"Tulsa"},
{"city":"Tunis"},
{"city":"Tunja"},
{"city":"Turfan"},
{"city":"Turku"},
{"city":"Turmero"},
{"city":"Tuxtla Gutiérrez"},
{"city":"Tuy Hòa"},
{"city":"Tuzla"},
{"city":"Tver"},
{"city":"Tychy"},
{"city":"Tyler"},
{"city":"Tyros"},
{"city":"Táriba"},
{"city":"Târgu Mureș"},
{"city":"Tébessa"},
{"city":"Türkistan"},
{"city":"Türkmenabat"},
{"city":"Tōkai"},
{"city":"Tšeboksary"},
{"city":"Tšeljabinsk"},
{"city":"Tšerkessk"},
{"city":"Tšernivtsi"},
{"city":"Tšita"},
{"city":"Ube"},
{"city":"Uberaba"},
{"city":"Uberlândia"},
{"city":"Ubá"},
{"city":"Udaipur"},
{"city":"Udon Thani"},
{"city":"Udupi"},
{"city":"Ueda"},
{"city":"Ufa"},
{"city":"Uijeongbu"},
{"city":"Uitenhage"},
{"city":"Uiwang"},
{"city":"Uji"},
{"city":"Ujjain"},
{"city":"Ulan Bator"},
{"city":"Ulan-Ude"},
{"city":"Ulanhot"},
{"city":"Ulanqab"},
{"city":"Ulhasnagar"},
{"city":"Uljanovsk"},
{"city":"Ulm"},
{"city":"Ulsan"},
{"city":"Umm Qasr"},
{"city":"Umuahia"},
{"city":"Umuarama"},
{"city":"Unaizah"},
{"city":"Upington"},
{"city":"Uppsala"},
{"city":"Uralsk"},
{"city":"Urasoe"},
{"city":"Urayasu"},
{"city":"Urdaneta"},
{"city":"Urganch"},
{"city":"Urmia"},
{"city":"Uruapan"},
{"city":"Uruguaiana"},
{"city":"Uruma"},
{"city":"Utsunomiya"},
{"city":"Uusi-Taipei"},
{"city":"Uyo"},
{"city":"Uşak"},
{"city":"Užhorod"},
{"city":"Vadodara"},
{"city":"Valdivia"},
{"city":"Valencia"},
{"city":"Valenzuela"},
{"city":"Valera"},
{"city":"Valinhos"},
{"city":"Valle de la Pascua"},
{"city":"Valledupar"},
{"city":"Vallejo"},
{"city":"Valparaíso"},
{"city":"Valparaíso de Goiás"},
{"city":"Van"},
{"city":"Vancouver"},
{"city":"Vantaa"},
{"city":"Varanasi"},
{"city":"Varginha"},
{"city":"Varna"},
{"city":"Varsova"},
{"city":"Vasai-Virar"},
{"city":"Vaughan"},
{"city":"Vehari"},
{"city":"Vellore"},
{"city":"Venetsia"},
{"city":"Venlo"},
{"city":"Ventura"},
{"city":"Veracruz"},
{"city":"Verona"},
{"city":"Vespasiano"},
{"city":"Viamão"},
{"city":"Vicenza"},
{"city":"Victorville"},
{"city":"Vigo"},
{"city":"Vijayawada"},
{"city":"Vila Franca de Xira"},
{"city":"Vila Nova de Famalicão"},
{"city":"Vila Nova de Gaia"},
{"city":"Vila Velha"},
{"city":"Villa Alemana"},
{"city":"Villa Mercedes"},
{"city":"Villa Nueva"},
{"city":"Villahermosa"},
{"city":"Villavicencio"},
{"city":"Villeurbanne"},
{"city":"Vilna"},
{"city":"Vinh"},
{"city":"Vinnytsja"},
{"city":"Virginia Beach"},
{"city":"Virrey del Pino"},
{"city":"Visakhapatnam"},
{"city":"Visalia, California"},
{"city":"Vitsebsk"},
{"city":"Vitória"},
{"city":"Vitória da Conquista"},
{"city":"Vitória de Santo Antão"},
{"city":"Vizianagaram"},
{"city":"Viña del Mar"},
{"city":"Việt Trì"},
{"city":"Vladimir"},
{"city":"Vlorë"},
{"city":"Volgograd"},
{"city":"Volta Redonda"},
{"city":"Volžski"},
{"city":"Voronež"},
{"city":"Votorantim"},
{"city":"Várzea Grande"},
{"city":"Várzea Paulista"},
{"city":"Västerås"},
{"city":"Vĩnh Long"},
{"city":"Vũng Tàu"},
{"city":"Wa"},
{"city":"Waco"},
{"city":"Wakayama"},
{"city":"Warangal"},
{"city":"Warnes"},
{"city":"Warren"},
{"city":"Warrington"},
{"city":"Washington"},
{"city":"Waterbury"},
{"city":"Waterloo"},
{"city":"Wau"},
{"city":"Wałbrzych"},
{"city":"Weifang"},
{"city":"Weihai"},
{"city":"Weinan"},
{"city":"Wellington"},
{"city":"Wenling"},
{"city":"Wenzhou"},
{"city":"West Bromwich"},
{"city":"West Covina"},
{"city":"West Palm Beach"},
{"city":"West Valley City"},
{"city":"Westminster"},
{"city":"Wichita"},
{"city":"Wichita Falls"},
{"city":"Wien"},
{"city":"Wiesbaden"},
{"city":"Wigan"},
{"city":"Willemstad"},
{"city":"Wilmington"},
{"city":"Windhoek"},
{"city":"Windsor"},
{"city":"Winnipeg"},
{"city":"Winston-Salem"},
{"city":"Winterthur"},
{"city":"Wolfsburg"},
{"city":"Wollongong"},
{"city":"Wolverhampton"},
{"city":"Worcester"},
{"city":"Wrexham"},
{"city":"Wrocław"},
{"city":"Wuhai"},
{"city":"Wuhan"},
{"city":"Wuhu"},
{"city":"Wuppertal"},
{"city":"Wuwei"},
{"city":"Wuxi"},
{"city":"Wuzhong"},
{"city":"Wuzhou"},
{"city":"Würzburg"},
{"city":"Włocławek"},
{"city":"Wŏnju"},
{"city":"Wŏnsan"},
{"city":"Xai-Xai"},
{"city":"Xalapa"},
{"city":"Xiamen"},
{"city":"Xiangcheng City"},
{"city":"Xiangtan"},
{"city":"Xiangyang"},
{"city":"Xianning"},
{"city":"Xianyang"},
{"city":"Xiaogan"},
{"city":"Xigazê"},
{"city":"Xinghua"},
{"city":"Xingning"},
{"city":"Xingtai"},
{"city":"Xining"},
{"city":"Xintai"},
{"city":"Xinxiang"},
{"city":"Xinyang"},
{"city":"Xinyu"},
{"city":"Xinzhou"},
{"city":"Xi’an"},
{"city":"Xuancheng"},
{"city":"Xuanwei"},
{"city":"Xuchang"},
{"city":"Xuzhou"},
{"city":"Xırdalan"},
{"city":"Yachiyo"},
{"city":"Yaizu"},
{"city":"Yalova"},
{"city":"Yamagata"},
{"city":"Yamaguchi"},
{"city":"Yamato"},
{"city":"Yamoussoukro"},
{"city":"Yanbu"},
{"city":"Yancheng"},
{"city":"Yangjiang"},
{"city":"Yangju"},
{"city":"Yangon"},
{"city":"Yangquan"},
{"city":"Yangsan"},
{"city":"Yangzhou"},
{"city":"Yantai"},
{"city":"Yan’an"},
{"city":"Yao"},
{"city":"Yaoundé"},
{"city":"Yaritagua"},
{"city":"Yasuj"},
{"city":"Yatsushiro"},
{"city":"Yavatmal"},
{"city":"Yazd"},
{"city":"Ya’an"},
{"city":"Yeoju"},
{"city":"Yeongju"},
{"city":"Yeosu"},
{"city":"Yibin"},
{"city":"Yichang"},
{"city":"Yichun"},
{"city":"Yidu, Hubei"},
{"city":"Yinchuan"},
{"city":"Yingkou"},
{"city":"Yingtan"},
{"city":"Yixing"},
{"city":"Yiyang"},
{"city":"Yogyakarta"},
{"city":"Yokkaichi"},
{"city":"Yokosuka"},
{"city":"Yola"},
{"city":"Yonago"},
{"city":"Yongin"},
{"city":"Yongzhou"},
{"city":"Yonkers"},
{"city":"York"},
{"city":"Yozgat"},
{"city":"Yueqing"},
{"city":"Yueyang"},
{"city":"Yulin"},
{"city":"Yulin, Guangxi"},
{"city":"Yuncheng"},
{"city":"Yunfu"},
{"city":"Yushu"},
{"city":"Yuxi"},
{"city":"Yuyao City"},
{"city":"Yuzhou"},
{"city":"Yên Bái"},
{"city":"Zabrze"},
{"city":"Zacatecas"},
{"city":"Zagazig"},
{"city":"Zagreb"},
{"city":"Zahedan"},
{"city":"Zakho"},
{"city":"Zama"},
{"city":"Zamboanga City"},
{"city":"Zamora"},
{"city":"Zanjan"},
{"city":"Zaoyang City"},
{"city":"Zaozhuang"},
{"city":"Zapopan"},
{"city":"Zaporižžja"},
{"city":"Zaria"},
{"city":"Zarqa"},
{"city":"Zhangjiagang"},
{"city":"Zhangjiajie"},
{"city":"Zhangjiakou"},
{"city":"Zhangye"},
{"city":"Zhangzhou"},
{"city":"Zhanjiang"},
{"city":"Zhaoqing"},
{"city":"Zhaotong"},
{"city":"Zhengzhou"},
{"city":"Zhenjiang"},
{"city":"Zhongshan"},
{"city":"Zhongwei"},
{"city":"Zhongxiang City"},
{"city":"Zhoukou"},
{"city":"Zhoushan"},
{"city":"Zhucheng"},
{"city":"Zhuhai"},
{"city":"Zhumadian"},
{"city":"Zhuzhou"},
{"city":"Zibo"},
{"city":"Zielona Góra"},
{"city":"Zigong (Sichuan)"},
{"city":"Ziguinchor"},
{"city":"Zinder"},
{"city":"Ziyang"},
{"city":"Zlatoust"},
{"city":"Zoetermeer"},
{"city":"Zomba (Malawi)"},
{"city":"Zonguldak"},
{"city":"Zoucheng"},
{"city":"Zunyi"},
{"city":"Zwolle"},
{"city":"Zürich"},
{"city":"Águas Lindas de Goiás"},
{"city":"Çanakkale"},
{"city":"Çorlu"},
{"city":"Çorum"},
{"city":"Örebro"},
{"city":"Öskemen"},
{"city":"Ürümqi"},
{"city":"Đà Lạt"},
{"city":"Đà Nẵng"},
{"city":"Đồng Hới"},
{"city":"İskenderun"},
{"city":"İzmir"},
{"city":"İzmit"},
{"city":"Łódź"},
{"city":"Ōgaki"},
{"city":"Ōita"},
{"city":"Ōme"},
{"city":"Ōmuta"},
{"city":"Ōnojō"},
{"city":"Ōsaki"},
{"city":"Ōshū"},
{"city":"Ōta (Gunma)"},
{"city":"Ōtsu"},
{"city":"Şanlıurfa"},
{"city":"Šahr-e Kord"},
{"city":"Šahty"},
{"city":"Šardža"},
{"city":"Šiauliai"},
{"city":"Šymkent"},
{"city":"Šīrāz"},
{"city":"Železnogorsk (Kurskin alue)"},
{"city":"Žytomyr"}
]

export default cities 